// This file is autogenerated by wrapSVGs.ts
// Changes to this file will be overwritten

import React from 'react'
import { SVG } from '~components/Icon/subcomponents/SVG'
import type { IconProps } from '~components/Icon/types'

export const AssignmentIcon = (props: IconProps): JSX.Element => {
  const svgContent = (
    <>
      <path
        fill="currentColor"
        d="M9 4a.486.486 0 0 0 .5-.5A.486.486 0 0 0 9 3a.486.486 0 0 0-.5.5.486.486 0 0 0 .5.5m4.995 15q-1.662 0-2.828-1.172Q10 16.658 10 14.995q0-1.662 1.172-2.828Q12.342 11 14.005 11q1.662 0 2.828 1.172Q18 13.342 18 15.005q0 1.662-1.172 2.828Q15.658 19 13.995 19m-.495-2h1v-1.5H16v-1h-1.5V13h-1v1.5H12v1h1.5zM5 7.5h8V6H5zM8.854 17H3.5q-.62 0-1.06-.44A1.45 1.45 0 0 1 2 15.5v-11q0-.618.44-1.06Q2.883 3 3.5 3h3.563a1.98 1.98 0 0 1 .697-1.073A1.92 1.92 0 0 1 9 1.5q.708 0 1.24.427.53.427.697 1.073H14.5q.619 0 1.06.44.44.442.44 1.06v5.375a6.4 6.4 0 0 0-.997-.25 6.1 6.1 0 0 0-2.003 0V9.25H5v1.5h5.542q-.459.354-.834.792-.375.436-.646.958H5V14h3.542a6 6 0 0 0-.063.5 3 3 0 0 0 0 .5q.02.48.115 1.01.094.532.26.99"
      />
    </>
  )
  return <SVG {...props}>{svgContent}</SVG>
}
