// This file is autogenerated by wrapSVGs.ts
// Changes to this file will be overwritten

import React from "react"
import { SVG, IconProps } from "~components/Icon/subcomponents/SVG"

export const BoldIcon = (props: IconProps): JSX.Element => {
  const svgContent = (
    <>
      <path
        fill="currentColor"
        d="M6 16V4h4.786c1.009 0 1.89.282 2.644.846.754.565 1.13 1.326 1.13 2.283 0 .686-.164 1.232-.492 1.64-.33.406-.714.717-1.153.931v.172c.643.214 1.152.55 1.526 1.007.372.457.559 1.05.559 1.778 0 1.071-.402 1.896-1.207 2.475-.805.579-1.764.868-2.876.868H6Zm2.415-7.157h2.174c.467 0 .859-.132 1.173-.397.315-.264.472-.589.472-.975 0-.37-.157-.692-.472-.963-.314-.272-.706-.408-1.174-.408H8.416v2.743Zm0 5.015h2.348c.572 0 1.018-.14 1.34-.42.321-.277.482-.638.482-1.081 0-.443-.16-.804-.482-1.082-.322-.279-.768-.418-1.34-.418H8.415v3Z"
      />
    </>
  )
  return <SVG {...props}>{svgContent}</SVG>
}
