// This file is autogenerated by wrapSVGs.ts
// Changes to this file will be overwritten

import React from "react"

import { SVG, IconProps } from "~components/Icon/subcomponents/SVG"

export const BookmarkOnIcon = (props: IconProps): JSX.Element => {
  const svgContent = (
    <>
      <path
        fill="currentColor"
        d="M15 1H5c-1.1 0-1.99.9-1.99 2L3 19l7-3 7 3V3c0-1.1-.9-2-2-2z"
      />
    </>
  )
  return <SVG {...props}>{svgContent}</SVG>
}
