// This file is autogenerated by wrapSVGs.ts
// Changes to this file will be overwritten

import React from "react"

import { SVG, IconProps } from "~components/Icon/subcomponents/SVG"

export const BullettedListIcon = (props: IconProps): JSX.Element => {
  const svgContent = (
    <>
      <path
        fill="currentColor"
        d="M3.812 11.292c-.36 0-.666-.125-.916-.375A1.247 1.247 0 0 1 2.521 10c0-.361.125-.667.375-.917s.555-.375.916-.375.667.125.917.375.375.556.375.917-.125.667-.375.917-.556.375-.917.375Zm0-4.98c-.36 0-.666-.125-.916-.374a1.25 1.25 0 0 1-.375-.917c0-.361.125-.667.375-.917s.555-.375.916-.375.667.125.917.375.375.556.375.917c0 .36-.125.666-.375.917-.25.25-.556.374-.917.374Zm0 9.938c-.36 0-.666-.125-.916-.375a1.247 1.247 0 0 1-.375-.917c0-.36.125-.666.375-.916s.555-.375.916-.375.667.125.917.375.375.555.375.916-.125.667-.375.917-.556.375-.917.375Zm2.834-.417v-1.75H17.5v1.75H6.646Zm0-4.958v-1.75H17.5v1.75H6.646Zm0-4.979v-1.75H17.5v1.75H6.646Z"
      />
    </>
  )
  return <SVG {...props}>{svgContent}</SVG>
}
