// This file is autogenerated by wrapSVGs.ts
// Changes to this file will be overwritten

import React, { useId } from "react"
import { SVG } from "~components/Icon/subcomponents/SVG"
import type { IconProps } from "~components/Icon/types"

export const CommentBankIcon = (props: IconProps): JSX.Element => {
  const uniqueId = useId()
  const svgContent = (
    <>
      <defs>
        <path
          id={uniqueId}
          d="M.667 17.333V1.917q0-.48.375-.865.374-.385.875-.385h14.166q.48 0 .865.385t.385.865V12.75q0 .48-.385.865-.385.384-.865.385H4zm9.229-9.729 2.02-1.042 2 1.042V1.917h-4.02z"
        />
      </defs>
      <use fill="currentColor" href={`#${uniqueId}`} fillRule="evenodd" />
    </>
  )
  return <SVG {...props}>{svgContent}</SVG>
}
