// This file is autogenerated by wrapSVGs.ts
// Changes to this file will be overwritten

import React from "react"
import { v4 as uuidv4 } from "uuid"
import { SVG, IconProps } from "~components/Icon/subComponents/SVG"

export const CommunicationsIcon = (props: IconProps): JSX.Element => {
  const uniqueId = uuidv4()
  const svgContent = (
    <>
      <defs>
        <path
          id={uniqueId}
          d="M17.2 5.2h-1.6v7.2H5.2V14c0 .44.36.8.8.8h8.8L18 18V6c0-.44-.36-.8-.8-.8ZM14 10V2.8c0-.44-.36-.8-.8-.8H2.8c-.44 0-.8.36-.8.8V14l3.2-3.2h8c.44 0 .8-.36.8-.8Z"
        />
      </defs>
      <use fill="currentColor" href={`#${uniqueId}`} fillRule="nonzero" />
    </>
  )
  return <SVG {...props}>{svgContent}</SVG>
}
