// This file is autogenerated by wrapSVGs.ts
// Changes to this file will be overwritten

import React from "react"

import { SVG, IconProps } from "~components/Icon/subComponents/SVG"

export const ConnectLineIcon = (props: IconProps): JSX.Element => {
  const svgContent = (
    <>
      <path d="M9.05 17.5h1.9v-2.05l3.55-3.9V6.775h-9v4.775l3.55 3.893V17.5ZM7.55 19v-2.95L4 12.15V6.775c0-.413.147-.766.44-1.06.294-.293.647-.44 1.06-.44h1.8l-.75.75V1h1.5v4.275h3.9V1h1.5v5.025l-.75-.75h1.8c.412 0 .766.147 1.06.44.293.294.44.647.44 1.06v5.375l-3.55 3.9V19h-4.9Z" />
    </>
  )
  return <SVG {...props}>{svgContent}</SVG>
}
