// This file is autogenerated by wrapSVGs.ts
// Changes to this file will be overwritten

import React, { useId } from "react"
import { SVG, IconProps } from "~components/Icon/subcomponents/SVG"

export const DashboardIcon = (props: IconProps): JSX.Element => {
  const uniqueId = useId()
  const svgContent = (
    <>
      <defs>
        <path
          id={uniqueId}
          d="M10.889 7.333H18V2h-7.111v5.333ZM2 10.89h7.111V2H2v8.889ZM10.889 18H18V9.111h-7.111V18ZM2 18h7.111v-5.333H2V18Z"
        />
      </defs>
      <use
        fill="currentColor"
        transform="translate(-2 -2)"
        href={`#${uniqueId}`}
        fillRule="evenodd"
      />
    </>
  )
  return <SVG {...props}>{svgContent}</SVG>
}
