// This file is autogenerated by wrapSVGs.ts
// Changes to this file will be overwritten

import React from "react"
import { SVG } from "~components/Icon/subcomponents/SVG"
import type { IconProps } from "~components/Icon/types"

export const DecreaseIndentIcon = (props: IconProps): JSX.Element => {
  const svgContent = (
    <>
      <path
        fill="currentColor"
        d="M9.183 13.909v-1.634H17v1.634zm-2.994-.7L3 10l3.19-3.19zM3 17v-1.633h14V17zM3 4.633V3h14v1.633zm6.183 3.092V6.09H17v1.634zm0 3.092V9.183H17v1.634z"
      />
    </>
  )
  return <SVG {...props}>{svgContent}</SVG>
}
