// This file is autogenerated by wrapSVGs.ts
// Changes to this file will be overwritten

import React, { useId } from "react"
import { SVG } from "~components/Icon/subcomponents/SVG"
import type { IconProps } from "~components/Icon/types"

export const DemographicsIcon = (props: IconProps): JSX.Element => {
  const uniqueId = useId()
  const svgContent = (
    <>
      <defs>
        <path
          id={uniqueId}
          d="M2 14.444v1.778h5.333v-1.778zM2 3.778v1.778h8.889V3.778zM10.889 18v-1.778H18v-1.778h-7.111v-1.777H9.11V18zM5.556 7.333v1.778H2v1.778h3.556v1.778h1.777V7.333zM18 10.89V9.11H9.111v1.778zm-5.333-3.556h1.777V5.556H18V3.778h-3.556V2h-1.777z"
        />
      </defs>
      <use fill="currentColor" href={`#${uniqueId}`} fillRule="nonzero" />
    </>
  )
  return <SVG {...props}>{svgContent}</SVG>
}
