// This file is autogenerated by wrapSVGs.ts
// Changes to this file will be overwritten

import React from "react"
import { SVG } from "~components/Icon/subcomponents/SVG"
import type { IconProps } from "~components/Icon/types"

export const IncreaseIndentIcon = (props: IconProps): JSX.Element => {
  const svgContent = (
    <>
      <path
        fill="currentColor"
        d="M3 17v-1.633h14V17zm0-3.791V6.81L6.209 10zm6.183.7v-1.634H17v1.634zM3 4.633V3h14v1.633zm6.183 3.092V6.09H17v1.634zm0 3.092V9.183H17v1.634z"
      />
    </>
  )
  return <SVG {...props}>{svgContent}</SVG>
}
