// This file is autogenerated by wrapSVGs.ts
// Changes to this file will be overwritten

import React from "react"
import { v4 as uuidv4 } from "uuid"
import { SVG, IconProps } from "~components/Icon/subComponents/SVG"

export const KioskWhiteIcon = (props: IconProps): JSX.Element => {
  const uniqueId = uuidv4()
  const svgContent = (
    <>
      <defs>
        <path
          id={uniqueId}
          d="M14.353 2H5.677c-.92 0-1.667.747-1.667 1.667v12.666c0 .92.747 1.667 1.667 1.667h8.676c.92 0 1.667-.747 1.667-1.667V3.667c0-.92-.433-1.667-1.353-1.667h-.314Z"
        />
      </defs>
      <g fill="none" fillRule="evenodd">
        <use fill="currentColor" href={`#${uniqueId}`} />
        <path
          fill="#FFF"
          d="M5 14.667h10V4H5zM9 16.333c0-.553.446-1 1-1s1 .447 1 1c0 .553-.446 1-1 1s-1-.447-1-1Z"
        />
      </g>
    </>
  )
  return <SVG {...props}>{svgContent}</SVG>
}
