// This file is autogenerated by wrapSVGs.ts
// Changes to this file will be overwritten

import React, { useId } from "react"
import { SVG } from "~components/Icon/subcomponents/SVG"
import type { IconProps } from "~components/Icon/types"

export const LogOutIcon = (props: IconProps): JSX.Element => {
  const uniqueId = useId()
  const svgContent = (
    <>
      <defs>
        <path
          id={uniqueId}
          d="M9.556 13.667 14 9.5 9.556 5.333 8.302 6.508l2.294 2.159H2v1.666h8.596l-2.294 2.159zM3.778 2C2.79 2 2 2.75 2 3.667V7h1.778V3.667h12.444v11.666H3.778V12H2v3.333C2 16.25 2.791 17 3.778 17h12.444C17.2 17 18 16.25 18 15.333V3.667C18 2.75 17.2 2 16.222 2z"
        />
      </defs>
      <use fill="currentColor" href={`#${uniqueId}`} fillRule="evenodd" />
    </>
  )
  return <SVG {...props}>{svgContent}</SVG>
}
