// This file is autogenerated by wrapSVGs.ts
// Changes to this file will be overwritten

import React from "react"

import { SVG, IconProps } from "~components/Icon/subcomponents/SVG"

export const MaximizeIcon = (props: IconProps): JSX.Element => {
  const svgContent = (
    <>
      <path
        fill="currentColor"
        d="M2 18v-7.018h1.965v3.697L14.679 3.965h-3.697V2H18v7.018h-1.965V5.32L5.321 16.035h3.697V18H2Z"
      />
    </>
  )
  return <SVG {...props}>{svgContent}</SVG>
}
