// This file is autogenerated by wrapSVGs.ts
// Changes to this file will be overwritten

import React from "react"
import { SVG } from "~components/Icon/subcomponents/SVG"
import type { IconProps } from "~components/Icon/types"

export const NumberedListIcon = (props: IconProps): JSX.Element => {
  const svgContent = (
    <>
      <path
        fill="currentColor"
        d="M2.5 16.667v-.834h1.667v-.416h-.834v-.834h.834v-.416H2.5v-.834h2.521v3.334zm.854-10v-2.5H2.5v-.834h1.688v3.334zm-.854 5v-.75l1.479-1.75H2.5v-.834h2.521v.771l-1.5 1.729h1.5v.834zm4.104 4.208v-1.75H17.5v1.75zm0-5v-1.75H17.5v1.75zm0-5v-1.75H17.5v1.75z"
      />
    </>
  )
  return <SVG {...props}>{svgContent}</SVG>
}
