// This file is autogenerated by wrapSVGs.ts
// Changes to this file will be overwritten

import React from "react"
import { SVG } from "~components/Icon/subcomponents/SVG"
import type { IconProps } from "~components/Icon/types"

export const PercentageIcon = (props: IconProps): JSX.Element => {
  const svgContent = (
    <>
      <path
        fill="currentColor"
        d="M16.59 2 2.003 16.587l1.414 1.415L18.004 3.414zM5.5 9.004c1.93 0 3.5-1.57 3.5-3.5s-1.57-3.5-3.5-3.5S2 3.574 2 5.504s1.57 3.5 3.5 3.5m0-5c.83 0 1.5.67 1.5 1.5s-.67 1.5-1.5 1.5-1.5-.67-1.5-1.5.67-1.5 1.5-1.5m5.5 10.5c0-1.93 1.57-3.5 3.5-3.5s3.5 1.57 3.5 3.5-1.57 3.5-3.5 3.5-3.5-1.57-3.5-3.5m2 0c0 .83.67 1.5 1.5 1.5s1.5-.67 1.5-1.5-.67-1.5-1.5-1.5-1.5.67-1.5 1.5"
        fillRule="evenodd"
        clipRule="evenodd"
      />
    </>
  )
  return <SVG {...props}>{svgContent}</SVG>
}
