// This file is autogenerated by wrapSVGs.ts
// Changes to this file will be overwritten

import React from "react"
import { SVG } from "~components/Icon/subcomponents/SVG"
import type { IconProps } from "~components/Icon/types"

export const PromotionIcon = (props: IconProps): JSX.Element => {
  const svgContent = (
    <>
      <path
        fill="currentColor"
        d="M9.992 2C14.415 2 18 5.584 18 10s-3.585 8-8.008 8C5.575 18 2 14.416 2 10s3.575-8 7.992-8m3.392 12.8-.896-3.856 2.984-2.584-3.936-.336L10 4.4 8.464 8.032l-3.936.336 2.983 2.584-.896 3.848L10 12.76z"
        fillRule="evenodd"
      />
    </>
  )
  return <SVG {...props}>{svgContent}</SVG>
}
