// This file is autogenerated by wrapSVGs.ts
// Changes to this file will be overwritten

import React, { useId } from "react"
import { SVG } from "~components/Icon/subcomponents/SVG"
import type { IconProps } from "~components/Icon/types"

export const RedoIcon = (props: IconProps): JSX.Element => {
  const uniqueId = useId()
  const svgContent = (
    <>
      <defs>
        <path
          id={uniqueId}
          d="M15.832 9.209A9.168 9.168 0 0 0 9.764 6.92C5.673 6.92 2.21 9.587 1 13.274l2.081.687a7.035 7.035 0 0 1 6.683-4.84 6.97 6.97 0 0 1 4.502 1.659l-3.182 3.18h7.92V6.04z"
        />
      </defs>
      <use fill="currentColor" href={`#${uniqueId}`} fillRule="evenodd" />
    </>
  )
  return <SVG {...props}>{svgContent}</SVG>
}
