// This file is autogenerated by wrapSVGs.ts
// Changes to this file will be overwritten

import React, { useId } from "react"
import { SVG, IconProps } from "~components/Icon/subcomponents/SVG"

export const ReportSharingIcon = (props: IconProps): JSX.Element => {
  const uniqueId = useId()
  const svgContent = (
    <>
      <defs>
        <path
          id={uniqueId}
          d="M8.223 6.89V3.335l-6.221 6.22 6.22 6.221v-3.643c4.444 0 7.554 1.422 9.776 4.532-.889-4.443-3.555-8.887-9.775-9.775Z"
        />
      </defs>
      <use
        fill="currentColor"
        transform="matrix(-1 0 0 1 20 0)"
        href={`#${uniqueId}`}
        fillRule="nonzero"
      />
    </>
  )
  return <SVG {...props}>{svgContent}</SVG>
}
