# Config for the Semantic Pull Requests GitHub app.
# https://github.com/probot/semantic-pull-requests

titleOnly: true
types:
  - feat
  - fix
  - docs
  - style
  - refactor
  - perf
  - test
  - build
  - ci
  - chore
  - revert
