# this is composite workflow that gets the repo ready for actions
# for docs how composite workflows work see https://wallis.dev/blog/composite-github-actions

name: Setup repository
description: Sets this repository up to allow efficient run of various github actions

runs:
  using: composite
  steps:
    - name: Install package manager via corepack
      run: |
        npm install -g corepack@v0.31.0
        corepack enable
      shell: bash

    - name: Cache pnpm store
      uses: actions/setup-node@v4
      with:
        node-version-file: package.json
        registry-url: https://npm.pkg.github.com/
        cache: 'pnpm'

    - name: Install dependencies
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        npm config set "//npm.pkg.github.com/:_authToken" "$GITHUB_TOKEN"
        pnpm install --frozen-lockfile

    - name: Install Playwright
      shell: bash
      run: |
        npx playwright install

    - name: Setup turborepo cache
      uses: rharkor/caching-for-turbo@v1.5
