# this is composite workflow that gets the repo ready for actions
# for docs how composite workflows work see https://wallis.dev/blog/composite-github-actions

name: Setup repository
description: Sets this repository up to allow efficient run of various github actions

runs:
  using: composite
  steps:
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: package.json
        registry-url: https://npm.pkg.github.com/

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 9
        run_install: false

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - name: Setup pnpm cache
      uses: actions/cache@v3
      with:
        path: ${{ env.STORE_PATH }}
        key: kaizen-${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        npm config set "//npm.pkg.github.com/:_authToken" "$GITHUB_TOKEN"
        pnpm install --frozen-lockfile

    - name: Install Playwright
      shell: bash
      run: |
        npx playwright install

    - name: Setup turborepo cache
      uses: dtinth/setup-github-actions-caching-for-turbo@v1
