version: "3.4"

x-defaults: &defaults
  volumes:
    - .:/workspace
  working_dir: /workspace
  command: /bin/sh -c "while sleep 1000; do :; done"
  environment:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_SESSION_TOKEN
    - AWS_DEFAULT_REGION
    - KAIZEN_DOMAIN_NAME
    - KAIZEN_DISTRIBUTION_ID
    - KAIZEN_BASE_PATH
    - GITHUB_STATUS_TOKEN

services:
  build:
    <<: *defaults
    build:
      context: .
      dockerfile: .buildkite/dockerfiles/build.Dockerfile

  publish:
    <<: *defaults
    build:
      context: .
      dockerfile: .buildkite/dockerfiles/publish.Dockerfile

  release:
    <<: *defaults
    build:
      context: .
      dockerfile: .buildkite/dockerfiles/release.Dockerfile
