module.exports = {
  projects: [
    "<rootDir>/packages/*",
    // "<rootDir>/packages/component-library",
    // "<rootDir>/packages/deprecated-component-library-helpers",
    // "<rootDir>/packages/design-tokens",
    // "<rootDir>/packages/react-deprecate-warning",

    "<rootDir>/draft-packages/*",
    // "<rootDir>/draft-packages/avatar",
    // "<rootDir>/draft-packages/badge",
    // "<rootDir>/draft-packages/button",
    // "<rootDir>/draft-packages/card",
    // "<rootDir>/draft-packages/collapsible",
    // "<rootDir>/draft-packages/divider",
    // "<rootDir>/draft-packages/dropdown",
    // "<rootDir>/draft-packages/dropdown-menu",
    // "<rootDir>/draft-packages/empty-state",
    // "<rootDir>/draft-packages/events",
    // "<rootDir>/draft-packages/filter-menu-button",
    // "<rootDir>/draft-packages/form",
    // "<rootDir>/draft-packages/guidance-block",
    // "<rootDir>/draft-packages/hero-card",
    // "<rootDir>/draft-packages/hero-panel",
    // "<rootDir>/draft-packages/hierarchical-menu",
    // "<rootDir>/draft-packages/hierarchical-select",
    // "<rootDir>/draft-packages/illustration",
    // "<rootDir>/draft-packages/likert-scale-legacy",
    // "<rootDir>/draft-packages/loading-placeholder",
    // "<rootDir>/draft-packages/loading-spinner",
    // "<rootDir>/draft-packages/menu",
    // "<rootDir>/draft-packages/modal",
    // "<rootDir>/draft-packages/popover",
    // "<rootDir>/draft-packages/select",
    // "<rootDir>/draft-packages/split-button",
    // "<rootDir>/draft-packages/table",
    // "<rootDir>/draft-packages/tabs",
    // "<rootDir>/draft-packages/tag",
    // "<rootDir>/draft-packages/tile",
    // "<rootDir>/draft-packages/title-block-zen",
    // "<rootDir>/draft-packages/tooltip",
    // "<rootDir>/draft-packages/user-interactions",
    // "<rootDir>/draft-packages/vertical-progress-step",
    // "<rootDir>/draft-packages/well",
    // "<rootDir>/draft-packages/zen-navigation-bar",

    "<rootDir>/legacy-packages/title-block",
  ],
}
