packages:
  - 'packages/**'
  - 'docs'
  - '!packages/components/future'
  - '!packages/components/next'
  - '!packages/utilities/v3'
  - '!packages/components/v1'
  - '!packages/components/v2'
  - '!packages/components/v3'
  - '!packages/design-tokens/js'
  - '!packages/components/alpha'
