packages:
  - 'packages/**'
  - 'docs'
  - '!packages/components/next'
  - '!packages/design-tokens/js'
  - '!packages/react-aria'
  - '!packages/react-aria-components'
  - '!packages/design-tokens/js'
  - '!packages/components/alpha'
