processes:
  README:
    command: './bin/readme.sh; tail -f /dev/null'

  install:
    command: devbox run setup

  build:
    command: pnpm turbo build --filter=@kaizen/tailwind --filter=@kaizen/design-tokens
    depends_on:
      install:
        condition: process_completed_successfully

  docs:
    command: pnpm dev
    depends_on:
      build:
        condition: process_completed_successfully
