version: "3.4"

x-defaults: &defaults
  volumes:
    - ..:/workspace
  working_dir: /workspace
  command: /bin/ash -c "while sleep 1000; do :; done"

services:
  build:
    <<: *defaults
    build:
      context: .
      dockerfile: dockerfiles/build.Dockerfile

  publish:
    <<: *defaults
    build:
      context: .
      dockerfile: dockerfiles/publish.Dockerfile

  release:
    <<: *defaults
    build:
      context: .
      dockerfile: dockerfiles/release.Dockerfile

  validate:
    <<: *defaults
    build:
      context: .
      dockerfile: dockerfiles/validate.Dockerfile
