env:
  KAIZEN_ROLE_ARN: ${BRANCH_ROLE_ARN}
  KAIZEN_DOMAIN_NAME: ${BRANCH_DOMAIN_NAME}
  KAIZEN_DISTRIBUTION_ID: ${BRANCH_DISTRIBUTION_ID}

x-defaults: &defaults
  agent_query_rules: ["queue=build-unrestricted"]
  plugins:
    - docker-compose#v3.0.3:
        run: build

steps:
  - name: ":balloon: Release"
    command: ".buildkite/scripts/release.sh"
    branches: "master"
    <<: *defaults
    plugins:
      - cultureamp/aws-assume-role#v0.1.0:
          role: "${KAIZEN_ROLE_ARN}"
      - docker-compose#v3.0.3:
          run: release

  - name: ":nut_and_bolt: Compile"
    command: ".buildkite/scripts/compile.sh"
    branches: "!master"
    <<: *defaults

  - name: ":mag: Lint"
    command: ".buildkite/scripts/lint.sh"
    branches: "!master"
    <<: *defaults

  - name: ":pencil2: Test"
    command: ".buildkite/scripts/test.sh"
    branches: "!master"
    <<: *defaults

  - name: ":package: Build (site)"
    command: ".buildkite/scripts/build-site.sh"
    artifact_paths: "./site.tar.gz"
    <<: *defaults

  - name: ":package: Build (storybook)"
    command: ".buildkite/scripts/build-storybook.sh"
    artifact_paths: "./storybook.tar.gz"
    <<: *defaults
    agent_query_rules: ["queue=build-unrestricted-large"]

  - name: ":rainbow: Build (chromatic)"
    command: ".buildkite/scripts/run-chromatic-build.sh"
    <<: *defaults
    agent_query_rules: ["queue=build-unrestricted-large"]
    plugins:
      - cultureamp/aws-assume-role#v0.1.0:
          role: "${KAIZEN_ROLE_ARN}"
      - docker-compose#v3.0.3:
          run: release

  - wait: ~
    continue_on_failure: true

  - name: ":seedling: Publish: ${KAIZEN_DOMAIN_NAME}${KAIZEN_BASE_PATH}"
    command: ".buildkite/scripts/publish.sh"
    env:
      KAIZEN_EXTRACT_ARTIFACTS: true
    <<: *defaults
    plugins:
      - cultureamp/aws-assume-role#v0.1.0:
          role: "${KAIZEN_ROLE_ARN}"
      - docker-compose#v3.0.3:
          run: publish
