env:
  KAIZEN_ROLE_ARN: ${BRANCH_ROLE_ARN}
  KAIZEN_DOMAIN_NAME: ${BRANCH_DOMAIN_NAME}
  KAIZEN_DISTRIBUTION_ID: ${BRANCH_DISTRIBUTION_ID}
  GITHUB_REGISTRY_TOKEN: ${GITHUB_REGISTRY_TOKEN}

x-defaults: &defaults
  agent_query_rules: ["queue=build-unrestricted"]
  plugins:
    - docker-compose#v3.9.0:
        run: build

steps:
  - name: ":balloon: Release"
    command: ".buildkite/scripts/release.sh"
    timeout_in_minutes: 15
    branches: "master"
    <<: *defaults
    plugins:
      - cultureamp/aws-assume-role#v0.2.0:
          role: "${KAIZEN_ROLE_ARN}"
      - docker-compose#v3.9.0:
          run: release
    notify:
      - slack: "#team_front_end_foundations"
        if: build.state == "failed"

  - name: ":hatched_chick: Release (canary)"
    command: ".buildkite/scripts/release.sh"
    timeout_in_minutes: 15
    branches: "canary"
    <<: *defaults
    plugins:
      - cultureamp/aws-assume-role#v0.2.0:
          role: "${KAIZEN_ROLE_ARN}"
      - docker-compose#v3.9.0:
          run: release

  - name: ":package: Build (site)"
    command: ".buildkite/scripts/build-site.sh"
    timeout_in_minutes: 15
    artifact_paths: "./site.tar.gz"
    <<: *defaults
    agent_query_rules: ["queue=build-unrestricted-large"]

  - name: ":package: Build (storybook)"
    command: ".buildkite/scripts/build-storybook.sh"
    timeout_in_minutes: 15
    artifact_paths: "./storybook.tar.gz"
    <<: *defaults
    agent_query_rules: ["queue=build-unrestricted-large"]

  - wait: ~
    continue_on_failure: true

  - name: ":seedling: Publish: ${KAIZEN_DOMAIN_NAME}${KAIZEN_BASE_PATH}"
    command: ".buildkite/scripts/publish.sh"
    timeout_in_minutes: 15
    # The canary branch is not able to update dev.cultureamp.design
    branches: "!canary"
    env:
      KAIZEN_EXTRACT_ARTIFACTS: true
    <<: *defaults
    plugins:
      - cultureamp/aws-assume-role#v0.2.0:
          role: "${KAIZEN_ROLE_ARN}"
      - docker-compose#v3.9.0:
          run: publish

  - block: ":rainbow: Build (chromatic)"
    prompt: "Check in Chromatic?"

  - name: ":rainbow: Build (chromatic)"
    command: ".buildkite/scripts/run-chromatic-build.sh"
    timeout_in_minutes: 15
    <<: *defaults
    agent_query_rules: ["queue=build-unrestricted-large"]
    plugins:
      - cultureamp/aws-assume-role#v0.2.0:
          role: "${KAIZEN_ROLE_ARN}"
      - docker-compose#v3.9.0:
          run: release
