env:
  KAIZEN_ROLE_ARN: ${BRANCH_ROLE_ARN}
  KAIZEN_DOMAIN_NAME: ${BRANCH_DOMAIN_NAME}
  KAIZEN_DISTRIBUTION_ID: ${BRANCH_DISTRIBUTION_ID}
  GITHUB_REGISTRY_TOKEN: ${GITHUB_REGISTRY_TOKEN}

x-defaults: &defaults
  agent_query_rules: ["queue=build-unrestricted"]
  plugins:
    - docker-compose#v3.9.0:
        run: build

steps:
  - name: ":balloon: Release"
    command: ".buildkite/scripts/release.sh"
    timeout_in_minutes: 30
    branches: "master"
    <<: *defaults
    plugins:
      - cultureamp/aws-assume-role#v0.2.0:
          role: "${KAIZEN_ROLE_ARN}"
      - docker-compose#v3.9.0:
          run: release
    notify:
      - slack: "#team_front_end_foundations"
        if: build.state == "failed"

  - name: ":hatched_chick: Release (canary)"
    command: ".buildkite/scripts/release.sh"
    timeout_in_minutes: 15
    branches: "canary"
    <<: *defaults
    plugins:
      - cultureamp/aws-assume-role#v0.2.0:
          role: "${KAIZEN_ROLE_ARN}"
      - docker-compose#v3.9.0:
          run: release

  - name: ":package: Build (storybook)"
    command: ".buildkite/scripts/build-storybook.sh"
    timeout_in_minutes: 15
    artifact_paths: "./storybook.tar.gz"
    <<: *defaults
    agent_query_rules: ["queue=build-unrestricted-large"]

  - name: ":nodesecurity: Audit JS Dependencies"
    command: .buildkite/scripts/audit-js.sh
    agents:
      queue: build-unrestricted
    plugins:
      - docker#v3.8.0:
          image: node:14
          environment:
            - GITHUB_REGISTRY_TOKEN

  - wait

  - name: ":seedling: Publish: ${KAIZEN_DOMAIN_NAME}"
    command: ".buildkite/scripts/publish.sh"
    timeout_in_minutes: 15
    # The canary branch is not able to update dev.cultureamp.design
    branches: "!canary"
    env:
      KAIZEN_EXTRACT_ARTIFACTS: true
    <<: *defaults
    plugins:
      - cultureamp/aws-assume-role#v0.2.0:
          role: "${KAIZEN_ROLE_ARN}"
      - docker-compose#v3.9.0:
          run: publish
