env:
  KAIZEN_ROLE_ARN: ${BRANCH_ROLE_ARN}
  KAIZEN_DOMAIN_NAME: ${BRANCH_DOMAIN_NAME}
  KAIZEN_DISTRIBUTION_ID: ${BRANCH_DISTRIBUTION_ID}
  GITHUB_REGISTRY_TOKEN: ${GITHUB_REGISTRY_TOKEN}

x-defaults: &defaults
  agent_query_rules: ["queue=build-unrestricted"]
  plugins:
    - docker-compose#v3.9.0:
        run: build

steps:
  - name: ":butterfly: Release"
    command: ".buildkite/scripts/release.sh"
    timeout_in_minutes: 15
    if: build.env("CHANGESETS_RELEASE") == "true" || (build.branch == "main" && build.author.name == "github-actions[bot]")
    <<: *defaults
    plugins:
      - cultureamp/aws-assume-role#v0.2.0:
          role: "${KAIZEN_ROLE_ARN}"
      - docker-compose#v3.9.0:
          run: release
    notify:
      - slack: "#wol_kaizen"
        if: build.state == "passed"
      - slack: "#wol_kaizen"
        if: build.state == "failed"

  - name: ":hatched_chick: Release (canary)"
    command: ".buildkite/scripts/release.sh"
    timeout_in_minutes: 15
    branches: "canary"
    <<: *defaults
    plugins:
      - cultureamp/aws-assume-role#v0.2.0:
          role: "${KAIZEN_ROLE_ARN}"
      - docker-compose#v3.9.0:
          run: release

  - name: ":package: Build (storybook)"
    branches: "main"
    command: ".buildkite/scripts/build-storybook.sh"
    timeout_in_minutes: 15
    artifact_paths: "./storybook.tar.gz"
    <<: *defaults
    agent_query_rules: ["queue=build-unrestricted-large"]

  - wait

  - name: ":seedling: Publish: ${KAIZEN_DOMAIN_NAME}"
    branches: "main"
    key: "publish-step"
    command: ".buildkite/scripts/publish.sh"
    timeout_in_minutes: 15
    env:
      KAIZEN_EXTRACT_ARTIFACTS: true
    <<: *defaults
    plugins:
      - cultureamp/aws-assume-role#v0.2.0:
          role: "${KAIZEN_ROLE_ARN}"
      - docker-compose#v3.9.0:
          run: publish

  - name: "LinearB: Record deployment time"
    command: bin/ci_noop
    branches: "main"
    plugins:
      - cultureamp/linearb-cycle-time#v1.1.1: ~
