env:
  KAIZEN_ROLE_ARN: ${BRANCH_ROLE_ARN}
  KAIZEN_DOMAIN_NAME: ${BRANCH_DOMAIN_NAME}
  KAIZEN_DISTRIBUTION_ID: ${BRANCH_DISTRIBUTION_ID}
  GITHUB_REGISTRY_TOKEN: ${GITHUB_REGISTRY_TOKEN}

x-defaults: &defaults
  agent_query_rules: ["queue=build-unrestricted"]
  plugins:
    - docker-compose#v3.9.0:
        run: build

steps:
  - name: ":sleuth_or_spy: Checking for release tag"
    key: "is_released"
    branches: "main"
    # we assume that all releases with have a tag and that tag with have a @ version format
    if: build.tag =~ /@(\d+\.\d+\.\d+)/

  - wait

  - name: ":package: Build (storybook)"
    branches: "main"
    depends_on: "is_released"
    command: ".buildkite/scripts/build-storybook.sh"
    timeout_in_minutes: 15
    artifact_paths: "./storybook.tar.gz"
    <<: *defaults
    agent_query_rules: ["queue=build-unrestricted-large"]

  - wait

  - name: ":seedling: Publish: ${KAIZEN_DOMAIN_NAME}"
    branches: "main"
    key: "publish-step"
    command: ".buildkite/scripts/publish.sh"
    timeout_in_minutes: 15
    env:
      KAIZEN_EXTRACT_ARTIFACTS: true
    <<: *defaults
    plugins:
      - cultureamp/aws-assume-role#v0.2.0:
          role: "${KAIZEN_ROLE_ARN}"
      - docker-compose#v3.9.0:
          run: publish

  - name: "LinearB: Record deployment time"
    command: bin/ci_noop
    branches: "main"
    plugins:
      - cultureamp/linearb-cycle-time#v1.1.1: ~
