// This file is autogenerated
// Changes to this file will be overwritten

import React from "react"
import { SVG } from "~components/__illustrations__/Icon/v1/subcomponents/SVG"
import type { IconProps } from "~components/__illustrations__/v1"

export const AddLinkIcon = (props: IconProps): JSX.Element => {
  const svgContent = (
    <>
      <path
        fill="currentColor"
        d="M9.125 14.167H5.833q-1.729 0-2.948-1.219T1.667 10t1.218-2.948q1.219-1.22 2.948-1.219h3.292v1.75H5.833q-1.04 0-1.729.688-.687.687-.687 1.729t.687 1.729q.688.688 1.729.688h3.292zm-2.458-3.292v-1.75h6.666v1.75zm4.208 3.292v-1.75h3.292q1.04 0 1.729-.688.687-.687.687-1.729t-.687-1.729q-.688-.688-1.729-.688h-3.292v-1.75h3.292q1.729 0 2.948 1.219T18.333 10t-1.218 2.948q-1.219 1.22-2.948 1.219z"
      />
    </>
  )
  return <SVG {...props}>{svgContent}</SVG>
}
