// This file is autogenerated
// Changes to this file will be overwritten

import React from "react"
import { SVG } from "~components/__illustrations__/Icon/v1/subcomponents/SVG"
import type { IconProps } from "~components/__illustrations__/v1"

export const BoldIcon = (props: IconProps): JSX.Element => {
  const svgContent = (
    <>
      <path
        fill="currentColor"
        d="M6 16V4h4.786q1.513 0 2.644.846 1.13.848 1.13 2.283 0 1.028-.492 1.64-.495.61-1.153.931v.172q.965.321 1.526 1.007.559.686.559 1.778 0 1.607-1.207 2.475T10.917 16zm2.415-7.157h2.174q.701 0 1.173-.397.472-.396.472-.975 0-.556-.472-.963-.472-.408-1.174-.408H8.416zm0 5.015h2.348q.857 0 1.34-.42.482-.416.482-1.081t-.482-1.082q-.482-.418-1.34-.418H8.415z"
      />
    </>
  )
  return <SVG {...props}>{svgContent}</SVG>
}
