// This file is autogenerated by wrapSVGs.ts
// Changes to this file will be overwritten

import React from "react"
import { SVG } from "~components/Icon/subcomponents/SVG"
import type { IconProps } from "~components/Icon/types"

export const BullettedListIcon = (props: IconProps): JSX.Element => {
  const svgContent = (
    <>
      <path
        fill="currentColor"
        d="M3.812 11.292q-.54 0-.916-.375A1.25 1.25 0 0 1 2.521 10q0-.542.375-.917t.916-.375q.542 0 .917.375t.375.917-.375.917-.917.375m0-4.98q-.54 0-.916-.374a1.25 1.25 0 0 1-.375-.917q0-.542.375-.917t.916-.375q.542 0 .917.375t.375.917q0 .54-.375.917-.375.375-.917.374m0 9.938q-.54 0-.916-.375a1.25 1.25 0 0 1-.375-.917q0-.54.375-.916.375-.375.916-.375.542 0 .917.375t.375.916-.375.917-.917.375m2.834-.417v-1.75H17.5v1.75zm0-4.958v-1.75H17.5v1.75zm0-4.979v-1.75H17.5v1.75z"
      />
    </>
  )
  return <SVG {...props}>{svgContent}</SVG>
}
