// This file is autogenerated
// Changes to this file will be overwritten

import React, { useId } from "react"
import { SVG } from "~components/__illustrations__/Icon/v1/subcomponents/SVG"
import type { IconProps } from "~components/__illustrations__/v1"

export const CameraIcon = (props: IconProps): JSX.Element => {
  const uniqueId = useId()
  const svgContent = (
    <>
      <defs>
        <path
          id={uniqueId}
          d="M2.25 2.25V0h1.5v2.25H6v1.5H3.75V6h-1.5V3.75H0v-1.5zm2.25 4.5V4.5h2.25V2.25H12l1.373 1.5h2.377c.825 0 1.5.675 1.5 1.5v9c0 .825-.675 1.5-1.5 1.5h-12c-.825 0-1.5-.675-1.5-1.5v-7.5zm5.25 6.75c2.07 0 3.75-1.68 3.75-3.75S11.82 6 9.75 6 6 7.68 6 9.75s1.68 3.75 3.75 3.75m-2.4-3.75c0 1.328 1.072 2.4 2.4 2.4s2.4-1.072 2.4-2.4-1.072-2.4-2.4-2.4a2.397 2.397 0 0 0-2.4 2.4"
        />
      </defs>
      <use
        fill="currentColor"
        transform="translate(1 2)"
        href={`#${uniqueId}`}
        fillRule="nonzero"
      />
    </>
  )
  return <SVG {...props}>{svgContent}</SVG>
}
