// This file is autogenerated
// Changes to this file will be overwritten

import React from "react"
import { SVG } from "~components/__illustrations__/Icon/v1/subcomponents/SVG"
import type { IconProps } from "~components/__illustrations__/v1"

export const CompetencyLibraryIcon = (props: IconProps): JSX.Element => {
  const svgContent = (
    <>
      <path
        fill="currentColor"
        d="M7.094 11.18a2.5 2.5 0 0 1-1.826-.745 2.43 2.43 0 0 1-.756-1.798q0-1.055.756-1.799a2.5 2.5 0 0 1 1.826-.745q1.07 0 1.826.745.756.744.756 1.799 0 1.053-.756 1.798a2.5 2.5 0 0 1-1.826.745"
      />
      <path
        fill="currentColor"
        d="M2.186 17q-.906 0-1.546-.63A2.06 2.06 0 0 1 0 14.846v-9.67q0-.893.64-1.534A2.1 2.1 0 0 1 2.186 3h9.604q.908 0 1.559.642.651.64.651 1.535v9.67q0 .893-.651 1.523T11.79 17zM2 14.401C3.27 12.92 5.041 12 7 12s3.73.92 5 2.401V5H2z"
        fillRule="evenodd"
        clipRule="evenodd"
      />
      <path fill="currentColor" d="M15 3h2v14h-2zM20 3h-2v14h2z" />
    </>
  )
  return <SVG {...props}>{svgContent}</SVG>
}
