// This file is autogenerated
// Changes to this file will be overwritten

import React from "react"
import { SVG } from "~components/__illustrations__/Icon/v1/subcomponents/SVG"
import type { IconProps } from "~components/__illustrations__/v1"

export const ConnectIcon = (props: IconProps): JSX.Element => {
  const svgContent = (
    <>
      <path
        fill="currentColor"
        d="M14.01 5 14 1h-2v4H8V1H6v4h-.01C5 4.99 4 5.99 4 6.99v5.49L7.5 16v3h5v-3l3.5-3.51v-5.5c0-1-1-2-1.99-1.99"
      />
    </>
  )
  return <SVG {...props}>{svgContent}</SVG>
}
