// This file is autogenerated
// Changes to this file will be overwritten

import React, { useId } from "react"
import { SVG } from "~components/__illustrations__/Icon/v1/subcomponents/SVG"
import type { IconProps } from "~components/__illustrations__/v1"

export const DashboardIcon = (props: IconProps): JSX.Element => {
  const uniqueId = useId()
  const svgContent = (
    <>
      <defs>
        <path
          id={uniqueId}
          d="M10.889 7.333H18V2h-7.111zM2 10.89h7.111V2H2zM10.889 18H18V9.111h-7.111zM2 18h7.111v-5.333H2z"
        />
      </defs>
      <use
        fill="currentColor"
        transform="translate(-2 -2)"
        href={`#${uniqueId}`}
        fillRule="evenodd"
      />
    </>
  )
  return <SVG {...props}>{svgContent}</SVG>
}
