// This file is autogenerated by wrapSVGs.ts
// Changes to this file will be overwritten

import React, { useId } from "react"
import { SVG } from "~components/Icon/subcomponents/SVG"
import type { IconProps } from "~components/Icon/types"

export const DeltaIcon = (props: IconProps): JSX.Element => {
  const uniqueId = useId()
  const svgContent = (
    <>
      <defs>
        <path
          id={uniqueId}
          d="M2 10c0-4.42 3.58-8 8-8s8 3.58 8 8-3.58 8-8 8-8-3.58-8-8m8-4.63-5.018 8.028h10.036zm2.131 6.401H7.87L10 8.36z"
        />
      </defs>
      <g fill="none" fillRule="evenodd">
        <circle cx="10" cy="10" r="7" />
        <use fill="currentColor" href={`#${uniqueId}`} />
      </g>
    </>
  )
  return <SVG {...props}>{svgContent}</SVG>
}
