// This file is autogenerated
// Changes to this file will be overwritten

import React from "react"
import { SVG } from "~components/__illustrations__/Icon/v1/subcomponents/SVG"
import type { IconProps } from "~components/__illustrations__/v1"

export const DeltaFlatIcon = (props: IconProps): JSX.Element => {
  const svgContent = (
    <>
      <path fill="currentColor" d="M4 9h12v2H4z" />
    </>
  )
  return <SVG {...props}>{svgContent}</SVG>
}
