// This file is autogenerated
// Changes to this file will be overwritten

import React from "react"
import { SVG } from "~components/__illustrations__/Icon/v1/subcomponents/SVG"
import type { IconProps } from "~components/__illustrations__/v1"

export const ItalicsIcon = (props: IconProps): JSX.Element => {
  const svgContent = (
    <>
      <path
        fill="currentColor"
        d="M5 16v-1.749h2.79l3.464-8.502h-2.71V4H16v1.749h-2.79L9.745 14.25h2.71V16z"
      />
    </>
  )
  return <SVG {...props}>{svgContent}</SVG>
}
