// This file is autogenerated
// Changes to this file will be overwritten

import React, { useId } from "react"
import { SVG } from "~components/__illustrations__/Icon/v1/subcomponents/SVG"
import type { IconProps } from "~components/__illustrations__/v1"

export const ListViewIcon = (props: IconProps): JSX.Element => {
  const uniqueId = useId()
  const svgContent = (
    <>
      <defs>
        <path
          id={uniqueId}
          d="M2 10.89h1.778V9.112H2zm0 3.556h1.778v-1.778H2zm0-7.112h1.778V5.556H2zm3.556 3.556h12.446V9.112H5.556zm0 3.556h12.446v-1.778H5.556zm0-8.89v1.778h12.446V5.556z"
        />
      </defs>
      <use fill="currentColor" href={`#${uniqueId}`} fillRule="evenodd" />
    </>
  )
  return <SVG {...props}>{svgContent}</SVG>
}
