// This file is autogenerated
// Changes to this file will be overwritten

import React from "react"
import { SVG } from "~components/__illustrations__/Icon/v1/subcomponents/SVG"
import type { IconProps } from "~components/__illustrations__/v1"

export const MaximizeIcon = (props: IconProps): JSX.Element => {
  const svgContent = (
    <>
      <path
        fill="currentColor"
        d="M2 18v-7.018h1.965v3.697L14.679 3.965h-3.697V2H18v7.018h-1.965V5.32L5.321 16.035h3.697V18z"
      />
    </>
  )
  return <SVG {...props}>{svgContent}</SVG>
}
