// This file is autogenerated
// Changes to this file will be overwritten

import React from "react"
import { SVG } from "~components/__illustrations__/Icon/v1/subcomponents/SVG"
import type { IconProps } from "~components/__illustrations__/v1"

export const RemoveLinkIcon = (props: IconProps): JSX.Element => {
  const svgContent = (
    <>
      <path
        fill="currentColor"
        d="m16.188 13.646-1.334-1.334q.854-.25 1.292-.885A2.46 2.46 0 0 0 16.583 10q0-1.042-.687-1.729t-1.729-.688h-3.396v-1.75h3.396q1.729 0 2.948 1.219T18.333 10q0 1.208-.593 2.156a4.3 4.3 0 0 1-1.552 1.49m-2.855-2.854-1.666-1.667h1.666zm3.105 8.041L1.167 3.562l1.229-1.229 15.271 15.271zm-7.313-4.666H5.833q-1.729 0-2.948-1.219T1.667 10q0-1.458.895-2.573a4.18 4.18 0 0 1 2.25-1.469L5.354 6l1.084 1.583h-.605q-1.04 0-1.729.688-.687.687-.687 1.729t.687 1.729q.688.688 1.729.688h3.292zm-2.458-3.292v-1.75h1.312l1.75 1.75z"
      />
    </>
  )
  return <SVG {...props}>{svgContent}</SVG>
}
