// This file is autogenerated
// Changes to this file will be overwritten

import React from "react"
import { SVG } from "~components/__illustrations__/Icon/v1/subcomponents/SVG"
import type { IconProps } from "~components/__illustrations__/v1"

export const SecurityTipIcon = (props: IconProps): JSX.Element => {
  const svgContent = (
    <>
      <path
        fill="currentColor"
        d="M10.182 0 2 3.636v5.455C2 14.136 5.49 18.855 10.182 20c4.69-1.145 8.182-5.864 8.182-10.91V3.637zm-.91 5.455h1.819v1.818H9.273zm0 3.636h1.819v5.455H9.273z"
      />
    </>
  )
  return <SVG {...props}>{svgContent}</SVG>
}
