// This file is autogenerated
// Changes to this file will be overwritten

import React from "react"
import { SVG } from "~components/__illustrations__/Icon/v1/subcomponents/SVG"
import type { IconProps } from "~components/__illustrations__/v1"

export const UnderlineIcon = (props: IconProps): JSX.Element => {
  const svgContent = (
    <>
      <path
        fill="currentColor"
        d="M10 13.667q-2.142 0-3.643-1.459t-1.5-3.562V3h2.229v5.646q0 1.187.846 2.021T10 11.5q1.222 0 2.068-.833.846-.834.846-2.021V3h2.23v5.646q0 2.104-1.5 3.562-1.502 1.46-3.644 1.459M4 17v-2h12v2z"
      />
    </>
  )
  return <SVG {...props}>{svgContent}</SVG>
}
