// This file is autogenerated
// Changes to this file will be overwritten

import React, { useId } from "react"
import { SVG } from "~components/__illustrations__/Icon/v1/subcomponents/SVG"
import type { IconProps } from "~components/__illustrations__/v1"

export const UserSettingsIcon = (props: IconProps): JSX.Element => {
  const uniqueId = useId()
  const svgContent = (
    <>
      <defs>
        <path
          id={uniqueId}
          d="M16.036 9.917a1.17 1.17 0 0 1-1.167-1.167c0-.643.524-1.166 1.167-1.166a1.168 1.168 0 0 1 0 2.333m2.477-.84c.012-.107.023-.217.023-.327s-.011-.22-.023-.326l.702-.55a.163.163 0 0 0 .04-.214l-.667-1.153a.16.16 0 0 0-.203-.073l-.83.333a2.5 2.5 0 0 0-.563-.327l-.127-.883a.163.163 0 0 0-.163-.14h-1.334a.16.16 0 0 0-.162.14l-.127.883q-.305.127-.563.327l-.83-.333a.17.17 0 0 0-.203.073l-.668 1.153a.17.17 0 0 0 .04.214l.703.55a3 3 0 0 0-.022.326c0 .114.01.22.022.327l-.702.55a.17.17 0 0 0-.041.213l.668 1.154c.039.073.126.103.203.073l.83-.333c.172.13.359.243.563.326l.127.884c.01.08.08.14.162.14h1.334c.083 0 .153-.06.163-.14l.127-.884q.305-.125.563-.326l.83.333c.073.027.164 0 .203-.073l.667-1.154a.17.17 0 0 0-.04-.213zM7.388 10a3.332 3.332 0 1 0 0-6.666 3.332 3.332 0 1 0 0 6.666m0 1.667C5.163 11.667.722 12.784.722 15v1.667h13.333V15c0-2.216-4.442-3.333-6.667-3.333"
        />
      </defs>
      <use fill="currentColor" href={`#${uniqueId}`} fillRule="evenodd" />
    </>
  )
  return <SVG {...props}>{svgContent}</SVG>
}
