import { pluginsSharedUi, rollupConfig } from "@kaizen/package-bundler";

export default rollupConfig({
  input: {
    index: "./src/index.ts",
    future: "./src/__future__/index.ts",
    actionsV1: "./src/__actions__/v1.ts",
    actionsV2: "./src/__actions__/v2.ts",
    containersV1: "./src/__containers__/v1.ts",
    containersV2: "./src/__containers__/v2.ts",
    contentV1: "./src/__content__/v1.ts",
    contentV2: "./src/__content__/v2.ts",
    formsV1: "./src/__forms__/v1.ts",
    formsV2: "./src/__forms__/v2.ts",
    IllustrationsV1: "./src/__Illustrations__/v1.ts",
    IllustrationsV2: "./src/__Illustrations__/v2.ts",
    layoutV1: "./src/__layout__/v1.ts",
    layoutV2: "./src/__layout__/v2.ts",
    loadingV1: "./src/__loading__/v1.ts",
    loadingV2: "./src/__loading__/v2.ts",
    notificationsV1: "./src/__notifications__/v1.ts",
    notificationsV2: "./src/__notifications__/v2.ts",
    overlaysV1: "./src/__overlays__/v1.ts",
    overlaysV2: "./src/__overlays__/v2.ts",
    overlaysV3: "./src/__overlays__/v3.ts",
    pickersV1: "./src/__pickers__/v1.ts",
    pickersV2: "./src/__pickers__/v2.ts",
    utilitiesV1: "./src/__utilities__/v1.ts",
    utilitiesV2: "./src/__utilities__/v2.ts",
    utilitiesV3: "./src/__utilities__/v3.ts",
    reactAriaV3: "./src/__react-aria__/index.ts",
    reactAriaComponentsV3: "./src/__react-aria-components__/index.ts",
    },
  plugins: pluginsSharedUi,
  alias: {
    entries: [
      { find: "~types", replacement: "src/types" },
      { find: "~utils", replacement: "src/utils" },
      { find: "~components", replacement: "src" },
    ],
  },
})
