export const TagVariants = [
  "default",
  "sentimentPositive",
  "sentimentNeutral",
  "sentimentNegative",
  "sentimentNone",
  "validationPositive",
  "validationInformative",
  "validationNegative",
  "validationCautionary",
  "statusLive",
  "statusDraft",
  "statusClosed",
  "statusAction",
] as const
