import { defaultTheme } from "@kaizen/design-tokens"

export const kzSpacing = {
  "spacing-2": ".125rem",
  "spacing-4": ".25rem",
  "spacing-8": ".5rem",
  "spacing-12": ".75rem",
  "spacing-16": "1rem",
  "spacing-24": "1.5rem",
  "spacing-32": "2rem",
  "spacing-40": "2.5rem",
  "spacing-48": "3rem",
  "spacing-56": "3.5rem",
  "spacing-64": "4rem",
  "spacing-72": "4.5rem",
  "spacing-80": "5rem",
  "spacing-96": "6rem",
  "spacing-112": "7rem",
  "spacing-128": "8rem",
  "spacing-160": "10rem",
  "spacing-200": "12.5rem",
  "spacing-240": "15rem",
  "spacing-280": "17.5rem",
  "spacing-320": "20rem",
  "spacing-xs": defaultTheme.spacing.xs,
  "spacing-sm": defaultTheme.spacing.sm,
  "spacing-md": defaultTheme.spacing.md,
  "spacing-lg": defaultTheme.spacing.lg,
  "spacing-xl": defaultTheme.spacing.xl,
  "spacing-xxl": defaultTheme.spacing.xxl,
  "spacing-xxxl": defaultTheme.spacing.xxxl,
  "spacing-xxxxl": defaultTheme.spacing.xxxxl,
  "spacing-xxxxxl": defaultTheme.spacing.xxxxxl,
}
