#!/usr/bin/env bash
set -eo pipefail

extract_artifact() {
  buildkite-agent artifact download "$1" .
  tar -xf "$1"
}

main() {
  export KAIZEN_BASE_PATH=""
  if [[ $BUILDKITE_BRANCH != "master" ]]; then
    KAIZEN_BASE_PATH="/${BUILDKITE_BRANCH}"
  fi

  if [[ -n $KAIZEN_EXTRACT_ARTIFACTS ]]; then
    echo "Extracting build artifacts..."
    extract_artifact "site.tar.gz"
    extract_artifact "storybook.tar.gz"
  fi
}

main

unset -f main extract_artifact
