#!/usr/bin/env bash
set -eo pipefail

extract-artifact() {
  buildkite-agent artifact download "$1" .
  tar -xf "$1"
}

main() {
  if [[ -n $EXTRACT_ARTIFACTS ]]; then
    extract-artifact "site.tar.gz"
    extract-artifact "storybook.tar.gz"
  fi
}

main

unset -f main extract-artifact
