#!/bin/bash
set -eo pipefail

# Exits non-zero unless run via `yarn <script>`
# Guarantees that the working directory is the workspace root, etc.

if [ -z "${INIT_CWD}" ]; then
  echo "❌ Please run me via \`yarn $(basename $0)\`"
  exit 1
fi
