// This file is autogenerated by wrapSVGs.ts
// Changes to this file will be overwritten

import React from "react"
import { SVG, SVGProps } from "~components/Icons/subComponents/SVG"
import { v4 as uuidv4 } from "uuid"

export const AddLinkIcon = (props: Omit<SVGProps, "children">): JSX.Element => {
  const uniqueId = uuidv4()
  return (
    <SVG {...props}>
      <path
        fill="currentColor"
        d="M9.125 14.167H5.833c-1.153 0-2.135-.406-2.948-1.219-.812-.813-1.218-1.795-1.218-2.948s.406-2.135 1.218-2.948c.813-.813 1.795-1.219 2.948-1.219h3.292v1.75H5.833c-.694 0-1.27.23-1.729.688-.458.458-.687 1.034-.687 1.729 0 .695.229 1.271.687 1.729.459.459 1.035.688 1.729.688h3.292v1.75Zm-2.458-3.292v-1.75h6.666v1.75H6.667Zm4.208 3.292v-1.75h3.292c.694 0 1.27-.23 1.729-.688.458-.458.687-1.034.687-1.729 0-.695-.229-1.271-.687-1.729-.459-.459-1.035-.688-1.729-.688h-3.292v-1.75h3.292c1.153 0 2.135.406 2.948 1.219.812.813 1.218 1.795 1.218 2.948s-.406 2.135-1.218 2.948c-.813.813-1.795 1.219-2.948 1.219h-3.292Z"
      />
    </SVG>
  )
}
