// This file is autogenerated by wrapSVGs.ts
// Changes to this file will be overwritten

import React from "react"
import { v4 as uuidv4 } from "uuid"
import { SVG, SVGProps } from "~components/Icons/subComponents/SVG"

const uniqueId = uuidv4()
export const ArrowUpIcon = (props: Omit<SVGProps, "children">): JSX.Element => (
  <SVG {...props}>
    <defs>
      <path
        id={uniqueId}
        d="m4 10 1.058 1.057L9.25 6.872V16h1.5V6.872l4.185 4.193L16 10l-6-6z"
      />
    </defs>
    <use fill="currentColor" href={`#${uniqueId}`} fillRule="evenodd" />
  </SVG>
)
