// This file is autogenerated by wrapSVGs.ts
// Changes to this file will be overwritten

import React from "react"
import { SVG, SVGProps } from "~components/Icons/subComponents/SVG"

export const CameraIcon = (props: Omit<SVGProps, "children">): JSX.Element => (
  <SVG {...props}>
    <defs>
      <path
        id="camera.icon.svg"
        d="M2.25 2.25V0h1.5v2.25H6v1.5H3.75V6h-1.5V3.75H0v-1.5h2.25Zm2.25 4.5V4.5h2.25V2.25H12l1.373 1.5h2.377c.825 0 1.5.675 1.5 1.5v9c0 .825-.675 1.5-1.5 1.5h-12c-.825 0-1.5-.675-1.5-1.5v-7.5H4.5Zm5.25 6.75c2.07 0 3.75-1.68 3.75-3.75C13.5 7.68 11.82 6 9.75 6 7.68 6 6 7.68 6 9.75c0 2.07 1.68 3.75 3.75 3.75Zm-2.4-3.75c0 1.328 1.072 2.4 2.4 2.4 1.328 0 2.4-1.072 2.4-2.4 0-1.328-1.072-2.4-2.4-2.4a2.397 2.397 0 0 0-2.4 2.4Z"
      />
    </defs>
    <use
      fill="currentColor"
      fill-rule="nonzero"
      transform="translate(1 2)"
      href="#camera.icon.svg"
    />
  </SVG>
)
