// This file is autogenerated by wrapSVGs.ts
// Changes to this file will be overwritten

import React from "react"
import { SVG, SVGProps } from "~components/Icons/subComponents/SVG"

export const CautionWhiteIcon = (
  props: Omit<SVGProps, "children">
): JSX.Element => (
  <SVG {...props}>
    <path
      fill="currentColor"
      d="M8.67 2.822 2.16 15.849A1.486 1.486 0 0 0 3.488 18h13.024a1.486 1.486 0 0 0 1.33-2.151L11.328 2.822c-.548-1.096-2.11-1.096-2.658 0Z"
    />
    <path
      fill="#FFF"
      d="M10.8 15H9.2v-1.6h1.6V15Zm0-3.2H9.2V7h1.6v4.8Z"
      clip-rule="evenodd"
      fillRule="evenodd"
    />
  </SVG>
)
