// This file is autogenerated by wrapSVGs.ts
// Changes to this file will be overwritten

import { SVG, SVGProps } from "~components/Icons/subComponents/SVG"

export const ChevronUpIcon = (
  props: Omit<SVGProps, "children">
): JSX.Element => (
  <SVG {...props}>
    <defs>
      <path
        id="chevron-up.icon.svg"
        d="M6.179 13.155 10 9.253l3.821 3.902 1.18-1.204L10 6.845l-5 5.106z"
      />
    </defs>
    <use fill="currentColor" fill-rule="evenodd" href="#chevron-up.icon.svg" />
  </SVG>
)
