// This file is autogenerated by wrapSVGs.ts
// Changes to this file will be overwritten

import React from "react"
import { SVG, SVGProps } from "~components/Icons/subComponents/SVG"
import { v4 as uuidv4 } from "uuid"

export const CommentBankIcon = (
  props: Omit<SVGProps, "children">
): JSX.Element => {
  const uniqueId = uuidv4()
  return (
    <SVG {...props}>
      <defs>
        <path
          id={uniqueId}
          d="M.667 17.333V1.917c0-.32.125-.608.375-.865s.541-.385.875-.385h14.166c.32 0 .608.128.865.385s.385.545.385.865V12.75c0 .32-.128.608-.385.865-.257.256-.545.385-.865.385H4L.667 17.333Zm9.229-9.729 2.02-1.042 2 1.042V1.917h-4.02v5.687Z"
        />
      </defs>
      <use fill="currentColor" href={`#${uniqueId}`} fillRule="evenodd" />
    </SVG>
  )
}
