// This file is autogenerated by wrapSVGs.ts
// Changes to this file will be overwritten

import React from "react"
import { SVG, SVGProps } from "~components/Icons/subComponents/SVG"

export const CompetencyLibraryIcon = (
  props: Omit<SVGProps, "children">
): JSX.Element => (
  <SVG {...props}>
    <path
      fill="currentColor"
      d="M7.094 11.18a2.507 2.507 0 0 1-1.826-.745 2.433 2.433 0 0 1-.756-1.798c0-.703.252-1.303.756-1.799a2.507 2.507 0 0 1 1.826-.745c.713 0 1.322.249 1.826.745s.756 1.096.756 1.799c0 .702-.252 1.302-.756 1.798a2.507 2.507 0 0 1-1.826.745Z"
    />
    <path
      fill="currentColor"
      fill-rule="evenodd"
      d="M2.186 17c-.604 0-1.12-.21-1.546-.63A2.06 2.06 0 0 1 0 14.846v-9.67c0-.595.213-1.107.64-1.534A2.104 2.104 0 0 1 2.186 3h9.604c.605 0 1.125.214 1.559.642.434.427.651.939.651 1.535v9.67c0 .595-.217 1.103-.651 1.523-.434.42-.954.63-1.559.63H2.186ZM2 14.401C3.27 12.92 5.041 12 7 12s3.73.92 5 2.401V5H2v9.401Z"
      clip-rule="evenodd"
    />
    <path fill="currentColor" d="M15 3h2v14h-2V3ZM20 3h-2v14h2V3Z" />
  </SVG>
)
