// This file is autogenerated by wrapSVGs.ts
// Changes to this file will be overwritten

import React from "react"
import { v4 as uuidv4 } from "uuid"
import { SVG, SVGProps } from "~components/Icons/subComponents/SVG"

const uniqueId = uuidv4()
export const DeltaWhiteIcon = (
  props: Omit<SVGProps, "children">
): JSX.Element => (
  <SVG {...props}>
    <defs>
      <path
        id={uniqueId}
        d="M2 10c0 4.42 3.58 8 8 8s8-3.58 8-8-3.58-8-8-8-8 3.58-8 8Z"
      />
    </defs>
    <g fill="none" fillRule="evenodd">
      <use fill="currentColor" href={`#${uniqueId}`} />
      <path fill="#FFF" d="m10 5.37-5.018 8.028h10.036z" />
      <path fill="currentColor" d="M12.131 11.771H7.87L10 8.36z" />
    </g>
  </SVG>
)
