// This file is autogenerated by wrapSVGs.ts
// Changes to this file will be overwritten

import React from "react"
import { SVG, SVGProps } from "~components/Icons/subComponents/SVG"
import { v4 as uuidv4 } from "uuid"

export const DeltaNegativeIcon = (
  props: Omit<SVGProps, "children">
): JSX.Element => {
  const uniqueId = uuidv4()
  return (
    <SVG {...props}>
      <path
        fill="currentColor"
        d="M6.775 16H16V6.775h-2.05V12.5L5.45 4 4 5.45l8.5 8.5H6.775V16z"
        fillRule="evenodd"
        clipRule="evenodd"
      />
    </SVG>
  )
}
