// This file is autogenerated by wrapSVGs.ts
// Changes to this file will be overwritten

import React from "react"

import { SVG, SVGProps } from "~components/Icons/subComponents/SVG"

export const DeltaFlatIcon = (
  props: Omit<SVGProps, "children">
): JSX.Element => {
  const svgContent = (
    <>
      <path fill="currentColor" d="M4 9h12v2H4V9z" />
    </>
  )
  const ariaLabel = props["aria-label"] ?? "delta flat icon"
  return (
    <SVG {...props} aria-label={ariaLabel}>
      {svgContent}
    </SVG>
  )
}
