// This file is autogenerated by wrapSVGs.ts
// Changes to this file will be overwritten

import React from "react"

import { SVG, IconProps } from "~components/Icons/subComponents/SVG"

export const EmptyWhiteIcon = (props: IconProps): JSX.Element => {
  const svgContent = (
    <>
      <g fill="none" fillRule="evenodd">
        <path
          fill="currentColor"
          d="M10 2c4.416 0 8 3.584 8 8s-3.584 8-8 8-8-3.584-8-8 3.584-8 8-8Z"
        />
        <path
          fill="#FFF"
          d="M10 16.4A6.398 6.398 0 0 1 3.6 10c0-3.536 2.864-6.4 6.4-6.4 3.536 0 6.4 2.864 6.4 6.4 0 3.536-2.864 6.4-6.4 6.4Z"
        />
      </g>
    </>
  )
  return <SVG {...props}>{svgContent}</SVG>
}
