// This file is autogenerated by wrapSVGs.ts
// Changes to this file will be overwritten

import React from "react"
import { v4 as uuidv4 } from "uuid"
import { SVG, SVGProps } from "~components/Icons/subComponents/SVG"

export const EngagementIcon = (
  props: Omit<SVGProps, "children">
): JSX.Element => {
  const uniqueId = uuidv4()
  const svgContent = (
    <>
      <defs>
        <path
          id={uniqueId}
          d="M15.423 5.396c0-.634.372-1.165 1.01-1.165.637 0 1.152.511 1.152 1.144l-.547 10.815c0 .894-1.432 2.737-3.122 2.737L9.997 19c-.83 0-1.442-.275-2.717-1.401 0 0-4.158-4.196-4.77-5.121-.415-.627.618-1.882 1.542-1.33.022.006 2.531 2.01 2.733 2.198.315.294.436.302.436.072 0-.151-.782-9.365-.782-9.365 0-.634.514-1.145 1.152-1.145.637 0 1.152.511 1.152 1.145l.421 5.027h.296l.05-6.935c0-.633.515-1.145 1.153-1.145.637 0 1.152.512 1.152 1.145l.155 6.94.41.01.203-6.187c0-.633.515-1.145 1.152-1.145.637 0 1.152.512 1.152 1.145l-.05 6.172h.4l.186-3.684Zm-3.386 10.77.373-.337c1.328-1.205 2.204-1.999 2.204-2.973 0-.794-.624-1.418-1.417-1.418-.45 0-.88.209-1.16.539a1.544 1.544 0 0 0-1.16-.539c-.793 0-1.417.624-1.417 1.418 0 .974.877 1.768 2.203 2.971l.374.34Z"
        />
      </defs>
      <use fill="currentColor" href={`#${uniqueId}`} fillRule="evenodd" />
    </>
  )
  return <SVG {...props}>{svgContent}</SVG>
}
