// This file is autogenerated by wrapSVGs.ts
// Changes to this file will be overwritten

import React from "react"
import { v4 as uuidv4 } from "uuid"
import { SVG, SVGProps } from "~components/Icons/subComponents/SVG"

const uniqueId = uuidv4()
export const FeedbackReportIcon = (
  props: Omit<SVGProps, "children">
): JSX.Element => (
  <SVG {...props}>
    <defs>
      <path
        id={uniqueId}
        d="M16.386 2c.873 0 1.57.697 1.613 1.57v9.59c0 .916-.74 1.613-1.613 1.613H5.182L2 18V3.612C2 2.697 2.697 2 3.57 2h12.816Zm-4.01 10.375h2.049V9.193h-2.05v3.182Zm-3.227 0h2.05V4.397h-2.05v7.978Zm-3.618 0H7.58v-5.58H5.53v5.58Z"
      />
    </defs>
    <use fill="currentColor" href={`#${uniqueId}`} fillRule="evenodd" />
  </SVG>
)
