// This file is autogenerated by wrapSVGs.ts
// Changes to this file will be overwritten

import React from "react"

import { SVG, SVGProps } from "~components/Icons/subComponents/SVG"

export const FullIcon = (props: Omit<SVGProps, "children">): JSX.Element => {
  const svgContent = (
    <>
      <path
        fill="currentColor"
        d="M10 2c-4.416 0-8 3.584-8 8s3.584 8 8 8 8-3.584 8-8-3.584-8-8-8Zm0 14.4A6.398 6.398 0 0 1 3.6 10c0-3.536 2.864-6.4 6.4-6.4 3.536 0 6.4 2.864 6.4 6.4 0 3.536-2.864 6.4-6.4 6.4Zm0-2.9a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7Z"
        fillRule="evenodd"
        clipRule="evenodd"
      />
    </>
  )
  const ariaLabel = props["aria-label"] ?? "full icon"
  return (
    <SVG {...props} aria-label={ariaLabel}>
      {svgContent}
    </SVG>
  )
}
