// This file is autogenerated by wrapSVGs.ts
// Changes to this file will be overwritten

import React from "react"
import { SVG, SVGProps } from "~components/Icons/subComponents/SVG"
import { v4 as uuidv4 } from "uuid"

export const ItalicsIcon = (props: Omit<SVGProps, "children">): JSX.Element => {
  const uniqueId = uuidv4()
  return (
    <SVG {...props}>
      <path
        fill="currentColor"
        d="M5 16v-1.749h2.79l3.464-8.502h-2.71V4H16v1.749h-2.79L9.745 14.25h2.71V16H5Z"
      />
    </SVG>
  )
}
