// This file is autogenerated by wrapSVGs.ts
// Changes to this file will be overwritten

import React from "react"
import { v4 as uuidv4 } from "uuid"
import { SVG, SVGProps } from "~components/Icons/subComponents/SVG"

const uniqueId = uuidv4()
export const MinusIcon = (props: Omit<SVGProps, "children">): JSX.Element => (
  <SVG {...props}>
    <defs>
      <path id={uniqueId} d="M13.996 10.833H6.011V9.167h7.985z" />
    </defs>
    <use fill="currentColor" href={`#${uniqueId}`} fillRule="evenodd" />
  </SVG>
)
