// This file is autogenerated by wrapSVGs.ts
// Changes to this file will be overwritten

import React from "react"
import { SVG, SVGProps } from "~components/Icons/subComponents/SVG"

export const NumberedListRtlIcon = (
  props: Omit<SVGProps, "children">
): JSX.Element => (
  <SVG {...props}>
    <path
      fill="currentColor"
      d="M2.5 15.875v-1.75h10.875v1.75H2.5Zm0-5v-1.75h10.875v1.75H2.5Zm0-5v-1.75h10.875v1.75H2.5Zm12.479 10.792v-.834h1.667v-.416h-.834v-.834h.834v-.416h-1.667v-.834H17.5v3.334h-2.521Zm.854-10v-2.5h-.854v-.834h1.688v3.334h-.834Zm-.854 5v-.75l1.5-1.75h-1.5v-.834H17.5v.771l-1.479 1.729H17.5v.834h-2.521Z"
    />
  </SVG>
)
