// This file is autogenerated by wrapSVGs.ts
// Changes to this file will be overwritten

import React from "react"
import { v4 as uuidv4 } from "uuid"
import { SVG, SVGProps } from "~components/Icons/subComponents/SVG"

export const PowerIcon = (props: Omit<SVGProps, "children">): JSX.Element => {
  const uniqueId = uuidv4()
  const svgContent = (
    <>
      <defs>
        <path
          id={uniqueId}
          d="M9.111 10.889h1.778V2H9.11v8.889Zm6.076-6.965-1.258 1.258A6.21 6.21 0 0 1 16.222 10a6.223 6.223 0 0 1-12.444 0A6.21 6.21 0 0 1 6.07 5.182L4.813 3.924A7.972 7.972 0 0 0 2 10a8 8 0 0 0 16 0 7.972 7.972 0 0 0-2.813-6.076Z"
        />
      </defs>
      <use fill="currentColor" href={`#${uniqueId}`} fillRule="evenodd" />
    </>
  )
  const ariaLabel = props["aria-label"] ?? "power icon"
  return (
    <SVG {...props} aria-label={ariaLabel}>
      {svgContent}
    </SVG>
  )
}
