// This file is autogenerated by wrapSVGs.ts
// Changes to this file will be overwritten

import React from "react"

import { SVG, SVGProps } from "~components/Icons/subComponents/SVG"

export const QuestionIcon = (
  props: Omit<SVGProps, "children">
): JSX.Element => {
  const svgContent = (
    <>
      <path
        fill="currentColor"
        d="M10 2c4.415 0 8 3.584 8 8s-3.585 8-8 8c-4.416 0-8-3.584-8-8s3.584-8 8-8Zm2.456 7.4a2.546 2.546 0 0 0 .744-1.8 3.2 3.2 0 1 0-6.4 0h1.6c0-.88.72-1.6 1.6-1.6.88 0 1.6.72 1.6 1.6 0 .44-.176.84-.472 1.128l-.992 1.008A3.22 3.22 0 0 0 9.2 12v.4h1.6c0-1.2.36-1.68.936-2.264l.72-.736ZM9.2 15.6h1.6V14H9.2v1.6Z"
        fillRule="evenodd"
      />
    </>
  )
  const ariaLabel = props["aria-label"] ?? "question icon"
  return (
    <SVG {...props} aria-label={ariaLabel}>
      {svgContent}
    </SVG>
  )
}
