// This file is autogenerated by wrapSVGs.ts
// Changes to this file will be overwritten

import { SVG, SVGProps } from "~components/Icons/subComponents/SVG"

export const QuestionsIcon = (
  props: Omit<SVGProps, "children">
): JSX.Element => (
  <SVG {...props}>
    <defs>
      <path
        id="questions.icon.svg"
        d="M13 13H3v1.667h10V13Zm0-6.667H3V8h10V6.333Zm-10 5h15V9.667H3v1.666ZM3 18h15v-1.667H3V18ZM3 3v1.667h15V3H3Z"
      />
    </defs>
    <use fill="currentColor" fill-rule="nonzero" href="#questions.icon.svg" />
  </SVG>
)
