// This file is autogenerated by wrapSVGs.ts
// Changes to this file will be overwritten

import React from "react"

import { SVG, SVGProps } from "~components/Icons/subComponents/SVG"

export const RemoveLinkIcon = (
  props: Omit<SVGProps, "children">
): JSX.Element => {
  const svgContent = (
    <>
      <path
        fill="currentColor"
        d="m16.188 13.646-1.334-1.334c.57-.167 1-.462 1.292-.885A2.46 2.46 0 0 0 16.583 10c0-.695-.229-1.271-.687-1.729-.459-.459-1.035-.688-1.729-.688h-3.396v-1.75h3.396c1.153 0 2.135.406 2.948 1.219.812.813 1.218 1.795 1.218 2.948 0 .805-.198 1.524-.593 2.156a4.314 4.314 0 0 1-1.552 1.49Zm-2.855-2.854-1.666-1.667h1.666v1.667Zm3.105 8.041L1.167 3.562l1.229-1.229 15.271 15.271-1.229 1.229Zm-7.313-4.666H5.833c-1.153 0-2.135-.406-2.948-1.219-.812-.813-1.218-1.795-1.218-2.948 0-.972.298-1.83.895-2.573a4.178 4.178 0 0 1 2.25-1.469L5.354 6l1.084 1.583h-.605c-.694 0-1.27.23-1.729.688-.458.458-.687 1.034-.687 1.729 0 .695.229 1.271.687 1.729.459.459 1.035.688 1.729.688h3.292v1.75Zm-2.458-3.292v-1.75h1.312l1.75 1.75H6.667Z"
      />
    </>
  )
  return <SVG {...props}>{svgContent}</SVG>
}
