// This file is autogenerated by wrapSVGs.ts
// Changes to this file will be overwritten

import { SVG, SVGProps } from "~components/Icons/subComponents/SVG"

export const RepeatsIcon = (props: Omit<SVGProps, "children">): JSX.Element => (
  <SVG {...props}>
    <defs>
      <path
        id="repeats.icon.svg"
        fill="currentColor"
        d="M4 5h10v3l4-4-4-4v3H2v6h2V5zm10 10H4v-3l-4 4 4 4v-3h12v-6h-2v4z"
      />
    </defs>
    <use fill="currentColor" fill-rule="evenodd" href="#repeats.icon.svg" />
  </SVG>
)
