<<<<<<< HEAD:packages/components/src/Icons/SecurityTipIcon.tsx
// This file is autogenerated by wrapSVGs.ts
// Changes to this file will be overwritten

import React from "react"

import { SVG, IconProps } from "~components/Icons/subComponents/SVG"

export const SecurityTipIcon = (props: IconProps): JSX.Element => {
  const svgContent = (
    <>
      <path
        fill="currentColor"
        d="M10.182 0 2 3.636v5.455C2 14.136 5.49 18.855 10.182 20c4.69-1.145 8.182-5.864 8.182-10.91V3.637L10.182 0Zm-.91 5.455h1.819v1.818H9.273V5.455Zm0 3.636h1.819v5.455H9.273V9.09Z"
      />
    </>
  )
  return <SVG {...props}>{svgContent}</SVG>
}
=======
import React from "react"
import { SVG, SVGProps } from "~components/SVG"

export const SecurityTipIcon = (
  props: Omit<SVGProps, "children">
): JSX.Element => (
  <SVG {...props}>
    <path
      d="M10.1818 0L2 3.63636V9.09091C2 14.1364 5.49091 18.8545 10.1818 20C14.8727 18.8545 18.3636 14.1364 18.3636 9.09091V3.63636L10.1818 0ZM9.27273 5.45455H11.0909V7.27273H9.27273V5.45455ZM9.27273 9.09091H11.0909V14.5455H9.27273V9.09091Z"
      fill="currentColor"
    />
  </SVG>
)

SecurityTipIcon.displayName = "SecurityTipIcon"
>>>>>>> 1bd1fa82f (WIP: migrate GenericNotification):packages/components/src/SVG/icons/SecurityTipIcon.tsx
