// This file is autogenerated by wrapSVGs.ts
// Changes to this file will be overwritten

import React from "react"
import { SVG, SVGProps } from "~components/Icons/subComponents/SVG"
import { v4 as uuidv4 } from "uuid"

export const SkipIcon = (props: Omit<SVGProps, "children">): JSX.Element => {
  const uniqueId = uuidv4()
  return (
    <SVG {...props}>
      <path
        fill="currentColor"
        d="M10 2c4.42 0 8 3.58 8 8s-3.58 8-8 8-8-3.58-8-8 3.58-8 8-8ZM6.8 12.935l4.272-3.068L6.8 6.8v6.135ZM11.6 6.8v6.135h1.005V6.8H11.6Z"
        fillRule="evenodd"
      />
    </SVG>
  )
}
