// This file is autogenerated by wrapSVGs.ts
// Changes to this file will be overwritten

import React from "react"

import { SVG, SVGProps } from "~components/Icons/subComponents/SVG"

export const StartIcon = (props: Omit<SVGProps, "children">): JSX.Element => {
  const svgContent = (
    <>
      <path
        fill="currentColor"
        d="M6 4H4v12h2V4Zm3.7 5.17H18v1.66H9.7l2.98 3L11.5 15l-5-5 5-5 1.18 1.18-2.99 2.99Z"
      />
    </>
  )
  return <SVG {...props}>{svgContent}</SVG>
}
