import { Theme } from "../types"

export const zenTheme: Theme = {
  themeKey: "zen",
  animation: {
    easingFunction: {
      easeInOut: "cubic-bezier(0.455, 0.03, 0.515, 0.955)",
      easeIn: "cubic-bezier(0.55, 0.085, 0.68, 0.53)",
      easeOut: "cubic-bezier(0.25, 0.46, 0.45, 0.94)",
      linear: "linear",
      bounceIn: "cubic-bezier(0.485, 0.155, 0.24, 1.245)",
      bounceOut: "cubic-bezier(0.485, 0.155, 0.515, 0.845)",
      bounceInOut: "cubic-bezier(0.76, -0.245, 0.24, 1.245)",
    },
    duration: {
      instant: "0ms",
      immediate: "100ms",
      rapid: "200ms",
      fast: "300ms",
      slow: "400ms",
      deliberate: "700ms",
    },
  },
  border: {
    solid: {
      borderWidth: "2px",
      borderRadius: "7px",
      borderStyle: "solid",
      borderColor: "#e1e2ea",
    },
    dashed: {
      borderWidth: "2px",
      borderRadius: "7px",
      borderStyle: "dashed",
    },
    borderless: {
      borderWidth: "2px",
      borderRadius: "7px",
      borderStyle: "solid",
      borderColor: "transparent",
    },
    focusRing: {
      borderWidth: "2px",
      borderRadius: "10px",
      borderStyle: "solid",
    },
  },
  color: {
    purple: {
      100: "#f0f1f4",
      200: "#e1e2ea",
      300: "#c4c5d4",
      400: "#a7a9c1",
      500: "#898ba9",
      600: "#6b6e94",
      700: "#4b4d68",
      800: "#35374a",
    },
    blue: {
      100: "#e6f0f7",
      200: "#cce1f0",
      300: "#99c3e1",
      400: "#4d95ca",
      500: "#0168b3",
      600: "#00518c",
      // Duplicate from Heart because it's new
      700: "#003157",
    },
    green: {
      100: "#e9f6f3",
      200: "#bce3dc",
      300: "#90d1c5",
      400: "#64bfae",
      500: "#21a38b",
      600: "#177261",
      // Duplicate from Heart because it's new
      700: "#22594a",
    },
    yellow: {
      100: "#fffae8",
      200: "#fff5d2",
      300: "#ffeba5",
      400: "#ffe278",
      500: "#ffce1e",
      // Duplicate from Heart because it's new
      600: "#c68600",
      // Duplicate from Heart because it's new
      700: "#876400",
    },
    red: {
      100: "#fcedef",
      200: "#fccfd4",
      300: "#fcaeb6",
      400: "#fc7c89",
      500: "#e22b3e",
      600: "#b02130",
      // Duplicate from Heart because it's new
      700: "#6c1e20",
    },
    orange: {
      100: "#fff1ee",
      200: "#fdd6cd",
      300: "#fdbaab",
      400: "#fc9e8a",
      500: "#fa7558",
      600: "#b85d4a",
      // Duplicate from Heart because it's new
      700: "#903c00",
    },
    // Should only exist in Heart but we need a consistent type.
    gray: {
      100: "#f9f9f9",
      200: "#f4f4f5",
      300: "#eaeaec",
      400: "#cdcdd0",
      500: "#8c8c97",
      600: "#524e56",
    },
    white: "#ffffff",
  },
  dataViz: {
    favorable: "#6b6e94",
    unfavorable: "#fccfd4",
  },
  layout: {
    contentMaxWidth: "1392px",
    contentSideMargin: "72px",
    mobileActionsDrawerHeight: "60px",
    navigationBarHeight: "72px",
    breakpoints: {
      medium: "768px",
      large: "1080px",
    },
  },
  shadow: {
    small: {
      boxShadow: "0 0 4px rgba(0, 0, 0, 0.09)",
    },
    large: {
      boxShadow: "0 0 12px rgba(0, 0, 0, 0.19)",
    },
  },
  spacing: {
    xs: "0.375rem",
    sm: "0.75rem",
    md: "1.5rem",
    lg: "2.25rem",
    xl: "3rem",
    xxl: "3.75rem",
    xxxl: "4.5rem",
    xxxxl: "5.25rem",
    xxxxxl: "6rem",
  },
  typography: {
    dataLarge: {
      fontFamily: '"Greycliff CF", "Noto Sans", Helvetica, Arial, sans-serif',
      fontWeight: 700,
      fontSize: "5.25rem",
      lineHeight: "5.25rem",
      letterSpacing: "normal",
    },
    dataLargeUnits: {
      fontFamily: '"Greycliff CF", "Noto Sans", Helvetica, Arial, sans-serif',
      fontWeight: 700,
      fontSize: "2.625rem",
      lineHeight: "5.25rem",
      letterSpacing: "normal",
    },
    dataMedium: {
      fontFamily: '"Greycliff CF", "Noto Sans", Helvetica, Arial, sans-serif',
      fontWeight: 700,
      fontSize: "3rem",
      lineHeight: "5rem",
      letterSpacing: "normal",
    },
    dataMediumUnits: {
      fontFamily: '"Greycliff CF", "Noto Sans", Helvetica, Arial, sans-serif',
      fontWeight: 700,
      fontSize: "1.5rem",
      lineHeight: "5rem",
      letterSpacing: "normal",
    },
    dataSmall: {
      fontFamily: '"Greycliff CF", "Noto Sans", Helvetica, Arial, sans-serif',
      fontWeight: 700,
      fontSize: "1.5rem",
      lineHeight: "1.5rem",
      letterSpacing: "normal",
    },
    dataSmallUnits: {
      fontFamily: '"Greycliff CF", "Noto Sans", Helvetica, Arial, sans-serif',
      fontWeight: 700,
      fontSize: "1.125rem",
      lineHeight: "1.5rem",
      letterSpacing: "normal",
    },
    display0: {
      fontFamily: '"Greycliff CF", "Noto Sans", Helvetica, Arial, sans-serif',
      fontWeight: 700,
      fontSize: "4.5rem",
      lineHeight: "4.5rem",
      letterSpacing: "-0.03em",
    },
    heading1: {
      fontFamily: '"Greycliff CF", "Noto Sans", Helvetica, Arial, sans-serif',
      fontWeight: 700,
      fontSize: "2.25rem",
      lineHeight: "2.25rem",
      letterSpacing: "-0.03em",
    },
    heading2: {
      fontFamily: '"Greycliff CF", "Noto Sans", Helvetica, Arial, sans-serif',
      fontWeight: 700,
      fontSize: "1.875rem",
      lineHeight: "2.25rem",
      letterSpacing: "-0.03em",
    },
    heading3: {
      fontFamily: '"Greycliff CF", "Noto Sans", Helvetica, Arial, sans-serif',
      fontWeight: 700,
      fontSize: "1.375rem",
      lineHeight: "1.5rem",
      letterSpacing: "-0.03em",
    },
    heading4: {
      fontFamily: '"Inter", "Noto Sans", Helvetica, Arial, sans-serif',
      fontWeight: 600,
      fontSize: "1.125rem",
      lineHeight: "1.5rem",
      letterSpacing: "normal",
    },
    heading5: {
      fontFamily: '"Inter", "Noto Sans", Helvetica, Arial, sans-serif',
      fontWeight: 600,
      fontSize: "1rem",
      lineHeight: "1.5rem",
      letterSpacing: "normal",
    },
    heading6: {
      fontFamily: '"Inter", "Noto Sans", Helvetica, Arial, sans-serif',
      fontWeight: 700,
      fontSize: "0.875rem",
      lineHeight: "1.5rem",
      letterSpacing: "normal",
    },
    paragraphIntroLede: {
      fontFamily: '"Inter", "Noto Sans", Helvetica, Arial, sans-serif',
      fontWeight: 400,
      fontSize: "1.25rem",
      lineHeight: "1.875rem",
      letterSpacing: "-0.5px",
    },
    paragraphBody: {
      fontFamily: '"Inter", "Noto Sans", Helvetica, Arial, sans-serif',
      fontWeight: 400,
      fontSize: "1rem",
      lineHeight: "1.5rem",
      letterSpacing: "normal",
    },
    paragraphSmall: {
      fontFamily: '"Inter", "Noto Sans", Helvetica, Arial, sans-serif',
      fontWeight: 400,
      fontSize: "0.875rem",
      lineHeight: "1.125rem",
      letterSpacing: "normal",
    },
    paragraphExtraSmall: {
      fontFamily: '"Inter", "Noto Sans", Helvetica, Arial, sans-serif',
      fontWeight: 400,
      fontSize: "0.75rem",
      lineHeight: "1.125rem",
      letterSpacing: "normal",
    },
    paragraphBold: {
      fontWeight: 600,
    },
    buttonPrimary: {
      fontFamily: '"Inter", "Noto Sans", Helvetica, Arial, sans-serif',
      fontWeight: 700,
      fontSize: "1.125rem",
      lineHeight: "1.5rem",
      letterSpacing: "normal",
    },
    buttonSecondary: {
      fontFamily: '"Inter", "Noto Sans", Helvetica, Arial, sans-serif',
      fontWeight: 500,
      fontSize: "1rem",
      lineHeight: "1.5rem",
      letterSpacing: "normal",
    },
  },
}
