import { Theme } from "../types"

export const zenTheme: Theme = {
  themeKey: "zen",
  animation: {
    easingFunction: {
      easeInOut: "cubic-bezier(0.455, 0.03, 0.515, 0.955)",
      easeIn: "cubic-bezier(0.55, 0.085, 0.68, 0.53)",
      easeOut: "cubic-bezier(0.25, 0.46, 0.45, 0.94)",
      linear: "linear",
      bounceIn: "cubic-bezier(0.485, 0.155, 0.24, 1.245)",
      bounceOut: "cubic-bezier(0.485, 0.155, 0.515, 0.845)",
      bounceInOut: "cubic-bezier(0.76, -0.245, 0.24, 1.245)",
    },
    duration: {
      instant: "0ms",
      immediate: "100ms",
      rapid: "200ms",
      fast: "300ms",
      slow: "400ms",
      deliberate: "700ms",
    },
  },
  border: {
    solid: {
      borderWidth: "2px",
      borderRadius: "7px",
      borderStyle: "solid",
      borderColor: "#e1e2ea",
    },
    dashed: {
      borderWidth: "2px",
      borderRadius: "7px",
      borderStyle: "dashed",
    },
    borderless: {
      borderWidth: "2px",
      borderRadius: "7px",
      borderStyle: "solid",
      borderColor: "transparent",
    },
    focusRing: {
      borderWidth: "2px",
      borderRadius: "10px",
      borderStyle: "solid",
    },
  },
  color: {
    wisteria: {
      100: "#F0F1F4",
      200: "#E1E2EA",
      300: "#C4C5D4",
      400: "#A7A9C1",
      500: "#898BA9",
      600: "#6B6E94",
      700: "#4B4D68",
      800: "#35374A",
    },
    cluny: {
      100: "#E6F0F7",
      200: "#CCE1F0",
      300: "#99C3E1",
      400: "#4D95CA",
      500: "#0168B3",
      600: "#00518C",
      // Duplicate from Heart because it's new
      700: "#003157",
    },
    seedling: {
      100: "#E9F6F3",
      200: "#BCE3DC",
      300: "#90D1C5",
      400: "#64BFAE",
      500: "#21A38B",
      600: "#177261",
      // Duplicate from Heart because it's new
      700: "#22594a",
    },
    yuzu: {
      100: "#FFFAE8",
      200: "#FFF5D2",
      300: "#FFEBA5",
      400: "#FFE278",
      500: "#FFCE1E",
      // Duplicate from Heart because it's new
      600: "#c68600",
      // Duplicate from Heart because it's new
      700: "#876400",
    },
    coral: {
      100: "#FCEDEF",
      200: "#FCCFD4",
      300: "#FCAEB6",
      400: "#FC7C89",
      500: "#E22B3E",
      600: "#B02130",
      // Duplicate from Heart because it's new
      700: "#6c1e20",
    },
    peach: {
      100: "#FFF1EE",
      200: "#FDD6CD",
      300: "#FDBAAB",
      400: "#FC9E8A",
      500: "#FA7558",
      600: "#B85D4A",
      // Duplicate from Heart because it's new
      700: "#903c00",
    },
    ash: "#ECECEF",
    stone: "#F6F6F6",
    white: "#FFFFFF",
    // Duplicate from Heart because it's new
    iron: "#8c8c97",
    // Duplicate from Heart because it's new
    slate: "#524e56",
  },
  DEPRECATED: {
    color: {
      lapis: "#253C64",
      ocean: "#1B7688",
      ink: "#3E4543",
      paper: "#F2EDDE",
    },
  },
  layout: {
    contentMaxWidth: "1392px",
    contentSideMargin: "72px",
    mobileActionsDrawerHeight: "60px",
    navigationBarHeight: "72px",
    breakpoints: {
      medium: "768px",
      large: "1080px",
    },
  },
  shadow: {
    small: {
      boxShadow: "0 0 4px rgba(0, 0, 0, 0.09)",
    },
    large: {
      boxShadow: "0 0 12px rgba(0, 0, 0, 0.19)",
    },
  },
  spacing: {
    xs: "0.375rem",
    sm: "0.75rem",
    md: "1.5rem",
    lg: "2.25rem",
    xl: "3rem",
    xxl: "3.75rem",
    xxxl: "4.5rem",
    xxxxl: "5.25rem",
    xxxxxl: "6rem",
  },
  typography: {
    dataLarge: {
      fontFamily: '"Greycliff CF", "Noto Sans", Helvetica, Arial, sans-serif',
      fontWeight: 700,
      fontSize: "5.25rem",
      lineHeight: "5.25rem",
      letterSpacing: "normal",
    },
    dataLargeUnits: {
      fontFamily: '"Greycliff CF", "Noto Sans", Helvetica, Arial, sans-serif',
      fontWeight: 700,
      fontSize: "2.625rem",
      lineHeight: "5.25rem",
      letterSpacing: "normal",
    },
    dataMedium: {
      fontFamily: '"Greycliff CF", "Noto Sans", Helvetica, Arial, sans-serif',
      fontWeight: 700,
      fontSize: "3rem",
      lineHeight: "5rem",
      letterSpacing: "normal",
    },
    dataMediumUnits: {
      fontFamily: '"Greycliff CF", "Noto Sans", Helvetica, Arial, sans-serif',
      fontWeight: 700,
      fontSize: "1.5rem",
      lineHeight: "5rem",
      letterSpacing: "normal",
    },
    dataSmall: {
      fontFamily: '"Greycliff CF", "Noto Sans", Helvetica, Arial, sans-serif',
      fontWeight: 700,
      fontSize: "1.5rem",
      lineHeight: "1.5rem",
      letterSpacing: "normal",
    },
    dataSmallUnits: {
      fontFamily: '"Greycliff CF", "Noto Sans", Helvetica, Arial, sans-serif',
      fontWeight: 700,
      fontSize: "1.125rem",
      lineHeight: "1.5rem",
      letterSpacing: "normal",
    },
    display0: {
      fontFamily: '"Greycliff CF", "Noto Sans", Helvetica, Arial, sans-serif',
      fontWeight: 700,
      fontSize: "4.5rem",
      lineHeight: "4.5rem",
      letterSpacing: "-0.03em",
    },
    heading1: {
      fontFamily: '"Greycliff CF", "Noto Sans", Helvetica, Arial, sans-serif',
      fontWeight: 700,
      fontSize: "2.25rem",
      lineHeight: "2.25rem",
      letterSpacing: "-0.03em",
    },
    heading2: {
      fontFamily: '"Greycliff CF", "Noto Sans", Helvetica, Arial, sans-serif',
      fontWeight: 700,
      fontSize: "1.875rem",
      lineHeight: "2.25rem",
      letterSpacing: "-0.03em",
    },
    heading3: {
      fontFamily: '"Greycliff CF", "Noto Sans", Helvetica, Arial, sans-serif',
      fontWeight: 700,
      fontSize: "1.375rem",
      lineHeight: "1.5rem",
      letterSpacing: "-0.03em",
    },
    heading4: {
      fontFamily: '"Inter", "Noto Sans", Helvetica, Arial, sans-serif',
      fontWeight: 600,
      fontSize: "1.125rem",
      lineHeight: "1.5rem",
      letterSpacing: "normal",
    },
    heading5: {
      fontFamily: '"Inter", "Noto Sans", Helvetica, Arial, sans-serif',
      fontWeight: 600,
      fontSize: "1rem",
      lineHeight: "1.5rem",
      letterSpacing: "normal",
    },
    heading6: {
      fontFamily: '"Inter", "Noto Sans", Helvetica, Arial, sans-serif',
      fontWeight: 700,
      fontSize: "0.875rem",
      lineHeight: "1.5rem",
      letterSpacing: "normal",
    },
    paragraphIntroLede: {
      fontFamily: '"Inter", "Noto Sans", Helvetica, Arial, sans-serif',
      fontWeight: 400,
      fontSize: "1.25rem",
      lineHeight: "1.875rem",
      letterSpacing: "-0.5px",
    },
    paragraphBody: {
      fontFamily: '"Inter", "Noto Sans", Helvetica, Arial, sans-serif',
      fontWeight: 400,
      fontSize: "1rem",
      lineHeight: "1.5rem",
      letterSpacing: "normal",
    },
    paragraphSmall: {
      fontFamily: '"Inter", "Noto Sans", Helvetica, Arial, sans-serif',
      fontWeight: 400,
      fontSize: "0.875rem",
      lineHeight: "1.125rem",
      letterSpacing: "normal",
    },
    paragraphExtraSmall: {
      fontFamily: '"Inter", "Noto Sans", Helvetica, Arial, sans-serif',
      fontWeight: 400,
      fontSize: "0.75rem",
      lineHeight: "1.125rem",
      letterSpacing: "normal",
    },
    paragraphBold: {
      fontWeight: 600,
    },
    buttonPrimary: {
      fontFamily: '"Inter", "Noto Sans", Helvetica, Arial, sans-serif',
      fontWeight: 700,
      fontSize: "1.125rem",
      lineHeight: "1.5rem",
      letterSpacing: "normal",
    },
    buttonSecondary: {
      fontFamily: '"Inter", "Noto Sans", Helvetica, Arial, sans-serif',
      fontWeight: 500,
      fontSize: "1rem",
      lineHeight: "1.5rem",
      letterSpacing: "normal",
    },
  },
}
