import * as React from "react";
export declare type InputType = "text" | "email" | "password";
export declare type InputStatus = "default" | "success" | "error";
export declare type InputProps = {
    id?: string;
    name?: string;
    automationId?: string;
    ariaDescribedBy?: string;
    className?: string;
    inputType?: InputType;
    defaultInputValue?: string;
    inputRef?: React.RefObject<HTMLInputElement>;
    placeholder?: string;
    disabled?: boolean;
    inputValue?: string;
    reversed?: boolean;
    status?: InputStatus;
    startIconAdornment?: React.ReactNode;
    endIconAdornment?: React.ReactNode;
    onChange?: (event: React.ChangeEvent<HTMLInputElement>) => any;
    onBlur?: (event: React.FocusEvent<HTMLInputElement>) => any;
    onFocus?: (event: React.FocusEvent<HTMLInputElement>) => any;
};
declare type Input = React.FunctionComponent<InputProps>;
declare const Input: Input;
export default Input;
