name: Changeset

on:
  push:
    branches:
      - 'main'
      - 'release/**' # Support release branches

jobs:
  version:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      hasChangesets: ${{ steps.changesets.outputs.hasChangesets }}
      hasPublished: ${{ steps.changesets.outputs.published }}
      publishedPackages: ${{ steps.changesets.outputs.publishedPackages }}
    env:
      GITHUB_TOKEN: ${{ github.token }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Create Release Pull Request or Publish to npm
        run: |
          npm config set "//registry.npmjs.org/:_authToken" "$NPM_TOKEN"
      - uses: changesets/action@v1
        id: changesets
        with:
          title: 'Changeset: Version packages'
          commit: 'version packages'
          version: pnpm ci:version
          publish: pnpm ci:publish

      - name: Trigger Documentation Generation
        if: steps.changesets.outputs.published == 'true'
        uses: ./.github/actions/trigger-docs
        with:
          published_packages: ${{ steps.changesets.outputs.publishedPackages }}
          buildkite_webhook_url: ${{ secrets.ENCHIRIDION_BUILDKITE_WEBHOOK_URL }}

  notify-slack-success:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: version
    if: needs.version.outputs.hasPublished == 'true'
    steps:
      - name: Send
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: 'C02NUQ27G56'
          slack-message: 'Packages have been published'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  notify-slack-failure:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: version
    if: ${{ always() && needs.version.result == 'failure' }}
    steps:
      - name: Send
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: 'C02NUQ27G56'
          slack-message: 'Publishing failed'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
