name: components

on:
  push:
    paths:
      - packages/components/**

jobs:
  test-components-compile:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: yarn workspace @kaizen/design-tokens build
      - run: yarn workspace @kaizen/tailwind build
      - run: yarn pkg:aio build
