name: Release notify

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # To check the github context
      - name: Dump Github context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Slack Notification on SUCCESS
        if: success()
        uses: pcolby/post-to-slack@v1
        with:
          url: ${{ secrets.SLACK_WEBHOOK_URL }}
          channel: "#wol_kaizen"
          username: "Release"
          text: >-
            ${{ github.event.release.tag_name}} is published!
            ${{ toJSON(github.event.release.body) }}
          iconEmoji: ":squid:"
