name: slack

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  notify:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Send
        uses: pcolby/post-to-slack@v1
        with:
          url: ${{ secrets.SLACK_WEBHOOK_URL }}
          channel: "#jasono_webhook_test"
          username: "Release"
          text: >-
            Release: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}
          iconUrl: https://picsum.photos/120/120
