name: slack

on: push

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      uses: slackapi/slack-github-action@v1.24.0
      with:
        # Slack channel id, channel name, or user id to post message.
        # See also: https://api.slack.com/methods/chat.postMessage#channels
        # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
        channel-id: "C05BTHKJYR0"
        # For posting a simple plain text message
        slack-message: "Hello"
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
