name: slack

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  notify:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Send
        uses: pcolby/post-to-slack@v1
        with:
          url: ${{ secrets.SLACK_WEBHOOK_URL }}
          text: Hello world!
